<div id="dashboard" class="container-fluid">
    <div class="row">
	<div class="col-sm-12">
            <div class="container-fluid">
                <!-- begin <row> -->
                <div class="row" align="center">
                    <div class="row shortcut-flex-box">

                        <section>

                        </section>
                                <div class="col-lg-3 col-sm-6 col-xs-12 box spacer-bottom-md">
                                    <div class="pane pane-default text-center shortcut-block no-margin sfb-box" style="display: none">
                                                <img src="https://account.sendinblue.com/public/assets/images/campaigns.png" alt="" width="40%" class="spacer-bottom-md" />
                                                <h3 class="spacer-bottom-md no-margin">Campañas</h3>
                                                <p class="spacer-bottom-md">Fidelice a sus contactos gracias al mejor editor de newsletters apto para móviles (responsivo)...¡con una entregabilidad óptima!</p>
                                                <div class="sb-block">
                                                        <div class="sb-content"><a href="https://my.sendinblue.com/camp/step1/type/classic">CREAR UNA NEWSLETTER</a></div>
                                                <button type="button" class="dropdown-toggle sb-dropdown-btn" data-toggle="dropdown">
                                                        <span class="caret"></span>
                                                </button>
                                                <ul class="dropdown-menu dropdown-list" role="menu">
                                                        <li><a href="https://my.sendinblue.com/camp/step1/type/sms">CREAR UNA CAMPAÑA SMS</a></li>
                                    <li><a href="https://my.sendinblue.com/camp/listing#sent_c">VER MIS CAMPAÑAS ANTERIORES</a></li>
                                                </ul>
                                                </div>
                                        </div>
                                </div>
                                <div class="col-lg-3 col-sm-6 col-xs-12 box spacer-bottom-md">
                                        <div class="pane pane-default text-center shortcut-block no-margin sfb-box">
                                                <img src="https://account.sendinblue.com/public/assets/images/contacts.png" alt="" width="40%" class="spacer-bottom-md" />
                                                <h3 class="spacer-bottom-md no-margin">Contactos</h3>
                                                <p class="spacer-bottom-md">Filtre y segmente sus contactos gracias a una herramienta de búsqueda potente e intuitiva que permite enviar campañas personalizadas.</p>
                                                <div class="sb-block">
                                                    <div class="sb-content"><a href="sendinblue/lists">GESTIONAR LISTAS</a></div>
                                                <button type="button" class="dropdown-toggle sb-dropdown-btn" data-toggle="dropdown">
                                                        <span class="caret"></span>
                                                </button>
                                                <ul class="dropdown-menu" role="menu">
                                                        <li><a href="https://my.sendinblue.com/users/list">GESTIONAR CONTACTOS</a></li>
                                                </ul>
                                                </div>
                                        </div>
                                </div>
                                <div class="col-lg-3 col-sm-6 col-xs-12 box spacer-bottom-md">
                                        <div class="pane pane-default text-center shortcut-block no-margin sfb-box">
                                                <img src="https://account.sendinblue.com/public/assets/images/Transactional.png" alt="" width="40%" class="spacer-bottom-md" />
                                                <h3 class="spacer-bottom-md no-margin">Transaccional</h3>
                                                <p class="spacer-bottom-md">Envíe e-mails o SMS personalizados en el momento oportuno con una entregabilidad óptima, potentes herramientas de seguimiento y un almacenamiento de datos ilimitado.</p>
                                                <div class="sb-block">
                                                        <div class="sb-content"><a href="https://app-smtp.sendinblue.com/statistics">VER ESTADÍSTICAS EMAILS</a></div>
                                                <button type="button" class="dropdown-toggle sb-dropdown-btn" data-toggle="dropdown">
                                                        <span class="caret"></span>
                                                </button>
                                                <ul class="dropdown-menu" role="menu">
                                                        <li><a href="https://app-sms.sendinblue.com/statistics">VER ESTADÍSTICAS SMS</a></li>
                                    <li><a href="https://my.sendinblue.com/camp/listing#temp_active_m">VER MIS PLANTILLAS SMTP</a></li>
                                                </ul>
                                                </div>
                                        </div>
                                </div>
                                <div class="col-lg-3 col-sm-6 col-xs-12 box spacer-bottom-md" style="display:none">
                                        <div class="pane pane-default text-center shortcut-block no-margin sfb-box">
                                                <img src="https://account.sendinblue.com/public/assets/images/Scenario.png" alt="" width="40%" class="spacer-bottom-md" />
                                                <h3 class="spacer-bottom-md no-margin">Automation</h3>
                                                <p class="spacer-bottom-md">Cree escenarios a medida gracias a las potentes herramientas de seguimiento de enlaces, de personas que abren los mensajes o que hacen clic, de eventos personalizados... ¡Y mucho más!</p>
                                                <div class="sb-block">
                                                        <div class="sb-content"><a href="https://automation.sendinblue.com/">CREAR UN ESCENARIO</a></div>
                                                <button type="button" class="dropdown-toggle sb-dropdown-btn" data-toggle="dropdown">
                                                        <span class="caret"></span>
                                                </button>
                                                <ul class="dropdown-menu" role="menu">
                                                        <li><a href="https://automation.sendinblue.com/dashboard">VER LAS ESTADÍSTICAS</a></li>
                                                </ul>
                                                </div>
                                        </div>
                                </div>
                    </div>
               </div>
            </div>
        <!-- end </row> --> 
    </div>
    </div>
</div>

