
<?php
        $execution_time_limit = 0;
        set_time_limit($execution_time_limit);

	$session = new \Zend\Session\Container("admin");
	
	try {   
            
                
		$dao = new \Application\Model\Dao\UsuarioDao();
		$pagos = $dao -> consultaGenerica("select  u.aPaterno, u.aMaterno, u.nombre,u.correo ,u.sexo, ue.noCorredor,u.fechaNacimiento, ev.nombre as nombreCarrera  ,dh.horario, DetE.direccion, u.idUsuario, ue.folio,e.nombre as equipo, ue.nocorredor,  DATE_FORMAT(de.fechaRealizacion, '%W ') as dia,DATE_FORMAT(de.fechaRealizacion, ' %M ') as mes, DATE_FORMAT(de.fechaRealizacion, ' %Y') as anio , DATE_FORMAT(de.fechaRealizacion, ' %d') as diaNum
	from Usuario u, UsuarioEquipo ue, Equipo e, DiaHit dh, DiaEvento de, DetallesEvento DetE, Evento ev, Pago p
	where ue.folio IS NOT NULL  and u.idusuario = ue.idusuario and ue.idEquipo = e.idEquipo and e.iddiahit = dh.idDiaHit and de.idDiaEvento = dh.idDiaEvento and de.idDetallesEvento= DetE.idDetallesEvento and DetE.idEvento = ev.idEvento and p.idEquipo = e.idEquipo  
	ORDER BY u.aPaterno LIMIT 0, 38");
		
		
		
			
		
	} catch (\Exception $ex) {
		$hayPagos = false;
	}


//Obtiene los folders

require('Mailin.php');
      $mailin = new Mailin("https://api.sendinblue.com/v2.0","NQGOIrgFEVKYxp51");
      
   
      
?>
<script>
	(function() {
		$("#navbarCollapse ul li").each(function() {
			$(this).removeClass("active");
		});
		$("#navbarCollapse ul").children().last().addClass("active");
		document.title = "Admin Main - InflaRun";
	})();
</script>



<h2>Saludos : <?php echo $this->texto?></h2>
<div id="dashboard" class="container-fluid">
    <div class="row">
	<div class="col-sm-12">
            <div class="container-fluid">
                <!-- begin <row> -->
                <!-- begin #main-content -->
<div id="main-content">

    <!-- begin #header -->
    <div id="header" class="spacer-bottom">

        <!-- begin .row -->
        <div class="row">

            <!-- begin .col -->
            <div class="col-md-12 clearfix">
                
                <h2 class="title-content-header">
                    <span>Listas</span>
                </h2>
                
                <div class="calltoaction-content-header">
                    <a id="modalimportcontacts" class="btn btn-success"><i class="fa fa-plus"></i> Agregar una nueva lista</a>
                </div>                
                
            </div>
            <!-- end .col -->

        </div>
        <!-- end .row -->

    </div>
    <!-- end #header -->

    <!-- begin #content -->
    <div id="content" class="spacer-bottom-lg">

<!-- begin if message -->
<div class="message-alert">
    <div id="message_content"></div>
</div>
<!-- end if message -->

    
        <!-- begin .row -->
        <div class="row spacer-bottom-sm">

            <!-- begin .col -->
            <div class="col-md-4">
                <div class="input-group">
                    <input class="form-control" id="editfoldername" style="display:none;" />
                    <select class="form-control" id="folder-list" style="display: block;"><option value="Su Primera Carpeta" selected="selected" list_id="1">Su Primera Carpeta</option><option value="" list_id="addFolder">Crear una carpeta</option></select>
                    <div class="input-group-btn">
                        <button type="button" class="btn btn-default edit" tabindex="-1"><i class="fa fa-pencil"></i></button>
                        <button type="button" class="btn btn-default delete" tabindex="-1"><i class="fa fa-trash"></i></button>
                    </div>
                </div>
            </div>
            <!-- end .col -->
            
            <!-- begin .col -->
            <div class="col-md-5">
                <div class="spacer-top-xs">
                    <b id="listCount"></b> 
                    <span class="listWord">Lista  </span>
                    <span class="folder-contacts"> & 
                        <b class="totalCount"><i class="fa fa-circle-o-notch fa-spin"></i></b>
                        <span class="contactWord">Contacto</span>
                    </span>
                </div>
            </div>
            <!-- end .col -->
            
            <!-- begin .col -->
            <div class="col-md-3">
                <div class="input-group">
                    <input type="text" name="filter" id="filter" class="form-control" placeholder="Búsqueda de lista" />
                    <div class="input-group-btn">
                        <button class="btn btn-default" type="button" name="search_lists_submit" id="search_lists_submit"><i class="fa fa-search"></i></button>
                    </div>
                </div>
            </div>
            <!-- end .col -->

        </div>
        <!-- end .row -->

        <!-- begin .row -->
        <div class="row">

            <!-- begin .col -->
            <div class="col-md-12">

                <div class="showLoader" id="showLoader"></div>
                <div id="message"></div>

                <!-- begin Listing -->
                <div id="listsDetails" class="pane pane-default">
                    
                    <div id="listsDetails" class="pane pane-default"><div class="table-responsive">                
                            <table class="table table-hover table-middle">                    
                                <thead>                        
                                    <tr>                            
                                        <th class="td-w-xs">Id</th>                            
                                        <th class="td-w-xlg">Nombre</th>                            
                                        <th class="td-w-xlg">Número de contactos</th>                            
                                        <th></th>                            
                                        <th class="td-w-sm listsDetails-th1">Acciones</th>                        
                                    </tr>                    
                                </thead>                    
                                <tbody>
                                    <tr id="list-4">                               
                                        <td class="text-muted">#4</td>                               
                                        <td class="listRename">Newsletter</td>                               
                                        <td><a href="https://my.sendinblue.com/users/list/id/4"><span>3.758</span> Contactos </a></td> 
                                        <td class="text-right text-muted"></td>
                                        <td class="text-right">                                
                                            <div class="btn-group ">                                    
                                                <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown">Acciones <span class="caret"></span></button>                                    
                                                <ul class="dropdown-menu dropdown-menu-right">                                        
                                                    <li><a href="https://my.sendinblue.com/users/list/id/4">
                                                            <i class="fa fa-user fa-fw"></i> Ver la lista</a></li>   
                                                            <li><a href="https://my.sendinblue.com/lists/settings/id/4">
                                                                    <i class="fa fa-wrench fa-fw"></i> Preferencias de la lista</a>
                                                            </li>                                        
                                                            <li><a href="#" id="replicate_list_4" class="replicate_class">
                                                                    <i class="fa fa-file fa-fw"></i> Duplicar</a></li>   
                                                                    <li class="save-and-add" data-toggle="modal" list_id="4" data-target1="#modal-add-contact"><a href="javascript:void(0);">
                                                                            <i class="fa fa-plus fa-fw"></i> Agregar un suscriptor</a></li>  
                                                                            <li class="save-and-add" data-toggle="modal" list_id="4" data-target1="#modal-import-files"><a href="#">
                                                                                    <i class="fa fa-download fa-fw"></i> Importar un archivo</a></li>                                        
                                                                                    <li class="save-and-add" data-toggle="modal" list_id="4" data-target1="#modal-copy-paste-contacts"><a href="#">
                                                                                            <i class="fa fa-share fa-fw"></i> Copiar/Pegar suscriptores</a></li>                                        
                                                                                            <li list_id="4" class="rename"><a href="javascript:void(0)">
                                                                                                    <i class="fa fa-pencil fa-fw"></i> Renombrar</a></li>
                                                                                                    <li><a href="javascript:void(0)" id="delete_list_4" class="delete_list"><i class="fa fa-trash fa-fw"></i> Eliminar</a></li> 
                                                </ul>                                
                                            </div>                            
                                        </td>                        
                                    </tr>
                                    <tr id="list-2">                               
                                        <td class="text-muted">#2</td>                               
                                        <td class="listRename">Lista 1</td>                               
                                        <td><a href="https://my.sendinblue.com/users/list/id/2"><span>2</span> Contactos </a></td>
                                        <td class="text-right text-muted"></td>
                                        <td class="text-right">                                
                                            <div class="btn-group ">                                    
                                                <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown">Acciones <span class="caret"></span></button>       
                                                <ul class="dropdown-menu dropdown-menu-right">                                        
                                                    <li><a href="https://my.sendinblue.com/users/list/id/2"><i class="fa fa-user fa-fw"></i> Ver la lista</a></li>
                                                    <li><a href="https://my.sendinblue.com/lists/settings/id/2"><i class="fa fa-wrench fa-fw"></i> Preferencias de la lista</a></li>
                                                    <li><a href="#" id="replicate_list_2" class="replicate_class"><i class="fa fa-file fa-fw"></i> Duplicar</a></li>   
                                                    <li class="save-and-add" data-toggle="modal" list_id="2" data-target1="#modal-add-contact"><a href="javascript:void(0);">
                                                            <i class="fa fa-plus fa-fw"></i> Agregar un suscriptor</a></li>                                        
                                                            <li class="save-and-add" data-toggle="modal" list_id="2" data-target1="#modal-import-files"><a href="#">
                                                                    <i class="fa fa-download fa-fw"></i> Importar un archivo</a></li>    
                                                                    <li class="save-and-add" data-toggle="modal" list_id="2" data-target1="#modal-copy-paste-contacts"><a href="#">
                                                                            <i class="fa fa-share fa-fw"></i> Copiar/Pegar suscriptores</a></li>                                        
                                                                            <li list_id="2" class="rename"><a href="javascript:void(0)"><i class="fa fa-pencil fa-fw"></i> Renombrar</a></li>
                                                                            <li><a href="javascript:void(0)" id="delete_list_2" class="delete_list"><i class="fa fa-trash fa-fw"></i> Eliminar</a></li> 
                                                </ul>                                
                                            </div>                            
                                        </td>                        
                                    </tr>
                                </tbody>
                            </table><
                            /div>
                        </div>
                </div>
                <!-- end Listing -->
                        
                <div class="text-center">
                    <div id="btn-view-more-wrap">
                        <a href="javascript:void(0);" class="btn btn-default spacer-top-xs spacer-bottom-md" id="btn-view-more">Ver más</a>
                    </div>
                    <div id="loader-view-more"></div>
                </div>

            </div>
            <!-- end .col -->

        </div>
        <!-- end .row -->

    </div>
    <!-- end #content -->
    <div class="clearfix"></div>

</div>
<!-- end #main-content -->
            </div>
        <!-- end </row> --> 
    </div>
    </div>
</div>

<div id="cuentaBody" class="container-fluid">
	<div class="row">
		<h2>Bienvenido, Administrador.</h2>
		<br>
		<?php if ($session -> offsetExists("message")): ?>
			<div class="alert alert-info fade in">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<?php
					echo $session -> offsetGet("message");
					$session -> offsetUnset("message");
				?>
			</div>
		<?php endif; ?>
		
		<div class="col-md-10 col-xs-9">
			<div class="panel panel-success">
				<div class="panel-heading">
					<strong>Pagos en Efectivo</strong>
				</div>
				<div class="panel-body">
					<div class="table-responsive">
						<table class="table table-hover">
							<thead>
								<tr>
									<th>Correo del usuario</th>
									<th>Número de pedido</th>
									<th>Número de transacción</th>
									<th>Fecha de expiración</th>
									<th>Acción</th>
								</tr>
							</thead>
							<tbody>
                                                                       
									<?php $contador = 1;foreach ($pagos as $pago):
                                                                            
                                                                            
                                                                       
                                                                        
                                                                        
                                                                        
                                                                        $to = $pago["correo"];
                                                                        $subject = "Comprobante de incripcion";
                                                                        $from = "ti@numeri.mx";
                                                                        $nombre = $pago["nombre"];    
                                                                        $paterno = $pago["aPaterno"];    
                                                                        $materno = $pago["aMaterno"];    
                                                                        $sexo = $pago["sexo"]; 
                                                                        $noCorredor = $pago["noCorredor"];       
                                                                        $carrera = $pago["nombreCarrera"]; 
                                                                        $hit = $pago["horario"];  
                                                                        $direccion =  $pago["direccion"];  
                                                                        $fechaNacimiento =  $pago["fechaNacimiento"];  
                                                                        $uuid =  $pago["idUsuario"];  
                                                                        $folio = $pago["folio"];
                                                                        $equipo = $pago["equipo"];    
                                                                        $nocorredor = $pago["nocorredor"];    
                                                                        $diaNum = $pago["diaNum"];    
                                                                          
                                                                        $dia = $pago["dia"]; 
                                                                        $domingo = "Sunday";
                                                                        
                                                                        if ( strcmp( $dia  , $domingo )== 1){
                                                                            $diaChido = "Domingo"; 
                                                                        }else
                                                                            
                                                                            $diaChido = "Sabado"; 
                                                                            
                                                                        
                                                                        $mes = "Septiembre";    
                                                                        $anio = "2016";    
                                                                        
                                                                        ?>
										<tr>
											
											<td><?php echo $to ?></td>
                                                                                        <td><?php echo $subject ; ?></td>
                                                                                        <td><?php echo $from ; ?></td>
                                                                                        <td><?php echo $nombre ; ?></td>
                                                                                        <td><?php echo $paterno; ?></td>
                                                                                        <td><?php echo $materno ; ?></td>
                                                                                        <td><?php echo $sexo ; ?></td>
                                                                                        <td><?php echo $noCorredor ; ?></td>
                                                                                        <td><?php echo $carrera ; ?></td>
                                                                                        <td><?php echo $hit ; ?></td>
                                                                                        <td><?php echo $direccion; ?></td>
                                                                                        <td><?php echo $fechaNacimiento; ?></td>  
                                                                                        <td><?php echo $uuid ; ?></td>
                                                                                        <td><?php echo $folio; ?></td>
                                                                                        <td><?php echo $equipo; ?></td>  
                                                                                        <td><?php echo $nocorredor ; ?></td>   
                                                                                        <td><?php echo $diaNum; ?></td>
                                                                                        
											
										</tr>
                                                                                
									<?php $contador++; 
                                                                        




                                                                      
        $imagedata = file_get_contents( "https://www.inflarun.mx/InflaRun/public/css/Imagenes/banner-inscripcion.png");
        $base64 = base64_encode($imagedata);

 
    $data = array( "to" => array($to =>"to whom!"),
        "from" => array($from, "from email!"),
        "subject" => $subject,
        "html" => "
       <html>
	<head>
		<title>Inscrito en InflaRun</title>
		<meta charset='UTF-8'>
		<meta name='viewport' content='width=device-width, initial-scale=1.0'>
		<style></style>
	</head>
	<body>
		<div class='container' align='center'>
			<img src=\"{https://www.inflarun.mx/InflaRun/public/css/Imagenes/banner-inscripcion.png}\"alt='image1' border='0'><br/>
		</div>
		<br>
      <div class='container-fluid'>
      <div class='row'>
			        <p>Estimado(a):". $nombre." </p>
			        <p>Agradecemos su inscripción a la carrera <strong>".$carrera."</strong> y anexamos su comprobante de inscripción. </p>
			        <br>
			        <h2>INFORMACIÓN PERSONAL</h2>
			        <p><strong>Nombre:</strong>". $nombre." <p>
			        <p><strong>Apellido paterno:</strong> ".$paterno."</p>
			        <p><strong>Apellido materno:</strong> ".$materno."</p>
			        <p><strong>Sexo:</strong> ".$sexo."</p>
			        <p><strong>Fecha de nacimiento:</strong> ".$fechaNacimiento."</p>
			        <br>
			        <h2>INFORMACIÓN DE LA CARRERA</h2>
			        <p><strong>Carrera:</strong> ".$carrera."</p>
			        <p><strong>Fecha:</strong> ".$diaChido ." ".$diaNum ." ". $mes ." ".$anio."</p>
			        <p><strong>Horario:</strong> ".$hit."</p>
			        <p><strong>Dirección:</strong> ".$direccion."</p>
			        <br>
			        <h2>INFORMACIÓN DE LA INSCRIPCIÓN</h2>
			        <p><strong>UUID de inscripción:</strong> ".$uuid."</p>
			        <p><strong>Folio de inscripción:</strong> ".$folio."</p>
			        <p><strong>Equipo:</strong> ".$equipo."</p>
			        <p><strong>Número de corredor:</strong> ".$noCorredor."</p>
			        <br>
			        <p>Imprime y firma esta forma. Llévala al registro para recoger tu paquete. Recuerda también llevar una
			        <strong>identificación oficial</strong>.</p>
			        <h3>FIRMA</h3>
			        <p>______________________________________________</p>
			        <br>
			        <div class='text-justify'>
			          <h4>Términos y Condiciones</h4>
			          <p>Admito que al firmar este documento conozco las bases de la convocatoria, que mis datos son verdaderos y
			          si fueran falsos seré descalificado del evento. Soy el único responsable de mi salud y de cualquier accidente
			          o deficiencia que pudiera causar alteración a mi salud física e incluso la muerte. Por esta razón libero al
			          comité organizador, a los patrocinadores, a las autoridades deportivas y a los prestadores de servicios de
			          cualquier daño que sufra. Así mismo, autorizo al comité organizador para utilizar mi imagen, voz y nombre, ya sea
			          total o parcialmente en lo relacionado al evento. Estoy conciente de que para participar en esta competencia debo
			          estar físicamente preparado para el esfuerzo que voy a realizar.</p>
			          <br>
			          <h4>Exoneraciones</h4>
			          <p>El paquete de correrdor se entregará el día del evento una hora antes del horario que seleccione al momento de
			          inscribirme. En tu paquete recibirás el número de competidor, tu playera y tu kit de participante. Es obligatorio
			          que el titular de la inscripción se presente a la entrega de paquetes a recoger el mismo llevando consigo una
			          identificación. No habrá módulo de entrega de grupos y no se le entregará paquete de competidor a ninguna otra persona
			          que no sea el titular de la inscripción y únicamente mostrando una identificación oficial. El corredor que por cualquier
			          motivo no recoja su paquete en el lugar y horario indicados perderá todo derecho derivado de su inscripción. Por ningún
			          motivo habrá cambio de horario ni de datos de competidor ni se permitirá transferir números.</p>
			        </div>
			      </div>
			    </div>
			  </body>
			  </html>",

            "headers" => array("Content-Type"=> "text/html; charset=iso-8859-1","X-param1"=> "value1", "X-param2"=> "value2","X-Mailin-custom"=>"my custom value", "X-Mailin-IP"=> "102.102.1.2", "X-Mailin-Tag" => "My tag"),
            "inline_image" => array("https://www.inflarun.mx/InflaRun/public/css/Imagenes/banner-inscripcion.png" => $base64));
 
    var_dump($mailin->send_email($data));                             
                                                                        endforeach;
                                                                        
                                                                        ?>
								
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
	<br>
</div>

