
<?php
        
//Obtiene los folders

require('Mailin.php');
$mailin = new Mailin("https://api.sendinblue.com/v2.0","NQGOIrgFEVKYxp51");
      
   
      
?>
<script>
    
    
        $(document).ready(function() {
            $("#deleteList").click(function() {
                       var str = "";
                     $( "#folder-list" ).change(function () {
                      
                      $( "#folder-list option:selected" ).each(function() {
                        str += $( this ).attr( "id" ) + " ";
                      });
                      
                      
                    })
                    .change();
                    window.location.href ="/sendinblue/deleteFolder/" + str;
            });
            
           
           var str2 ="" 
           $( "#folder-list option:selected" ).each(function() {
                        str2 += $( this ).attr( "nombre" ) + " ";
                    });
           
           $( "#nombreCarpeta strong" ).text(str2);
           
           // ---------- Valor para confirmacion de eliminacion de carpeta
           var str2 ="" 
           $( "#folder-list option:selected" ).each(function() {
                        str2 += $( this ).attr( "nombre" ) + " ";
                    });
           
           $( "#nombreCarpeta strong" ).text(str2);
           
            // ---------- Valor para confirmacion de eliminacion de lista
            
          
         
           
           
           var str4 ='';
           $( "#folder-list option:selected" ).each(function() {
                str4 += $( this ).attr( "id" );
            });
           
           
           
           $("#agregarCarpeta a").click(function() {
                    var str3 ="" 
                    str3 = '/sendinblue/updateFolder/'+ str4+'/'+ $('#listupdatename').val();
                    //$( "#test" ).text(str3);
                    window.location.href = str3;
            });
            
            $("#agregarLista a").click(function() {
                    var str5 ="" 
                    str5 = '/sendinblue/addList/'+ str4+'/'+ $('#listaddname').val();
                    //$( "#test" ).text(str5);
                    window.location.href = str5;
            });
            
            
            //Obtiene valor del ide de lista al hacer click en el link
           $("a").click(function() {
                  var idLista = $(this).attr("id");
                  var nombrelista = $(this).attr("nombreLista");
                   //$( "#test" ).text(oID);
                   //$( "#test2" ).text(nombrelista);
                    $( "#actualizarLista" ).attr("identificador",idLista);
                    $( "#confElimLista" ).attr("identificador",idLista);
                    $( "#cambiarNombreLista strong" ).text(nombrelista);
                    
                    //$( "#test2" ).text($( "#confElimLista" ).attr("#identificador"););
            });
            
            //Actualiza la lista al hacer click
            
            $("#actualizarLista a").click(function() {
                    var str6 ="" 
                    str6 = '/sendinblue/updateList/'+ str4+'/'+ $('#listaupdatename').val() + '/' + $( "#actualizarLista" ).attr("identificador");
                    //$( "#test" ).text(str6);
                    window.location.href = str6;
            });
            
            //Elimina la lista al hacer click

             $("#confElimLista a").click(function() {
                    var str7 ="" 
                    str7 = '/sendinblue/deleteLista/'+ str4+'/dfdf' + '/' + $( "#confElimLista" ).attr("identificador");
                    //$( "#test" ).text(str7);
                    window.location.href = str7;
            })
            
            
            
            
           
            
        });
        
        
</script>



<div id="dashboard" class="container-fluid">
    <div class="row">
	<div class="col-sm-12">
            <div class="container-fluid">
                <!-- begin <row> -->
                <!-- begin #main-content -->
                <div id="main-content">

                    <!-- begin #header -->
                    <div id="header" class="spacer-bottom">

                        <!-- begin .row -->
                        <div class="row">

                            <!-- begin .col -->
                            <div class="col-md-12 clearfix">

                                <h2 class="title-content-header">
                                    <span>  Listas</span>
                                </h2>

                                <div data-toggle="modal" data-target="#nuevaLista" class="calltoaction-content-header" >
                                    <a   id="modalimportcontacts" class="btn btn-success"><i class="fa fa-plus"></i> Agregar una nueva lista</a>
                                </div>                

                            </div>
                            <!-- end .col -->

                        </div>
                        <!-- end .row -->

                    </div>
                    <!-- end #header -->

                    <!-- begin #content -->
                    <div id="content" class="spacer-bottom-lg">

                <!-- begin if message -->
                <div class="message-alert">
                    <div id="message_content"></div>
                </div>
                <!-- end if message -->


                        <!-- begin .row -->
                        <div class="row spacer-bottom-sm">

                            <!-- begin .col -->
                            <div class="col-md-4">
                                <div class="input-group">
                                    <div class="input-group-btn"> 
                                        <button  type="button" class="btn btn-default edit" tabindex="-1"><i class="fa fa-folder-open"></i> </button>
                                     </div>
                                    <select class="form-control" id="folder-list" style="display: block;" onchange="location = this.value"    >
                                        <?php
                                            foreach ($this->ListAllFolder['data']['folders'] as $key => $value)  
                                            {  
                                                if($value["id"] == $id){
                                                    echo "<option value=".$this -> basePath()."/sendinblue/lists/".$value["id"]."  selected='selected' nombre=". $value["name"]." id=". $value["id"].">". $value["name"]."</option>";
                                                }else{
                                                    echo "<option  value=".$this -> basePath()."/sendinblue/lists/".$value["id"]."   nombre=". $value["name"]." id=". $value["id"].">". $value["name"]."</option>";        
                                                }
                                            } 
                                        ?>
                                    </select>
                                    <div class="input-group-btn">
                                        <button data-toggle="modal" data-target="#nuevoFolder" type="button" class="btn btn-default edit" tabindex="-1"><i class="fa fa-plus"></i></button>
                                        <button data-toggle="modal" data-target="#ActualizarFolder" class="btn btn-default edit" tabindex="-1"><i class="fa fa-pencil"></i></button>
                                        <button data-toggle="modal" data-target="#confimation_modal" type="button" class="btn btn-default delete" id="deleteFolder" tabindex="-1"><i class="fa fa-trash"></i></button>
                                    </div>
                                </div>
                            </div>
                            <!-- end .col -->

                            <!-- begin .col -->
                            <div class="col-md-5">
                                <div class="spacer-top-xs">
                                    <b id="listCount"></b> 
                                    <span class="listWord"> <?php echo sizeof($this->FolderDetails['data'][0]['lists']);?> <strong> Listas</strong>  </span>
                                    <span class="folder-contacts"> & 
                                        <span class="contactWord"> <?php echo $this->FolderDetails['data'][0]['total_subscribers'];?> <strong>Contactos</strong></span>
                                    </span>
                                </div>
                            </div>
                            <!-- end .col -->

                            <!-- begin .col -->
                            <div class="col-md-3">
                                <div class="input-group">
                                    <input type="text" name="filter" id="filter" class="form-control" placeholder="Búsqueda de lista" />
                                    <div class="input-group-btn">
                                        <button class="btn btn-default" type="button" name="search_lists_submit" id="search_lists_submit"><i class="fa fa-search"></i></button>
                                    </div>
                                </div>
                            </div>
                            <!-- end .col -->

                        </div>
                        <!-- end .row -->

                        <!-- begin .row -->
                        <div class="row">

                            <!-- begin .col -->
                            <div class="col-md-12">

                                <div class="showLoader" id="showLoader"></div>
                                <div id="message"></div>

                                <!-- begin Listing -->
                                <div id="listsDetails" class="pane pane-default">

                                    <div id="listsDetails" class="pane pane-default"><div class="table-responsive">                
                                            <table class="table table-hover table-middle">                    
                                                
                                                    <?php 
                                                    if(sizeof($this->allLists['data']['lists']) == 0){
                                                            echo " <tr id='list-4'>                               
                                                                                          
                                                                <div >                                    
                                                                   <p> Esta carpeta esta vacia</p>                        
                                                                </div>                        
                                                        </tr>";
                                                    }else{
                                                        echo "<thead>                        
                                                    <tr>                            
                                                        <th class='td-w-xs'>Id</th>                            
                                                        <th class='td-w-xlg'>Nombre</th>                            
                                                        <th class='td-w-xlg'>Número de contactos</th>                            
                                                        <th></th>                            
                                                        <th class='td-w-sm listsDetails-th1'>Acciones</th>                        
                                                    </tr>                    
                                                </thead>      ";
                                                        foreach ($this->allLists['data']['lists'] as $key => $value)  
                                            {  
                                                //echo $key ."|". $value . "<br />";
                                                
                                                        echo " 
                                                                          
                                                <tbody><tr '>                               
                                                            <td class='text-muted'>#". $value['id']."</td>                               
                                                            <td class='listRename' >". $value['name']."</td>                               
                                                            <td><a href='".  $this -> basePath() ."/sendinblue/users/". $value['id'] ."/".$this->id."'><span>". $value['total_subscribers']."</span> Contactos </a></td> 
                                                            <td class='text-right text-muted'></td>
                                                            <td class='text-right'>                                
                                                                <div class='btn-group '>                                    
                                                                    <button type='button' class='btn btn-default btn-sm dropdown-toggle' data-toggle='dropdown'>Acciones <span class='caret'></span></button>                                    
                                                                    <ul class='dropdown-menu dropdown-menu-right'>                                        
                                                                        <li><a href='https://my.sendinblue.com/users/list/id/4'>
                                                                                <i class='fa fa-user fa-fw'></i> Ver la lista</a></li>   
                                                                                <li><a href='https://my.sendinblue.com/lists/settings/id/4'>
                                                                                        <i class='fa fa-wrench fa-fw'></i> Preferencias de la lista</a>
                                                                                </li>                                        
                                                                                <li><a href='#' id='replicate_list_4' class='replicate_class'>
                                                                                        <i class='fa fa-file fa-fw'></i> Duplicar</a>
                                                                                </li>   
                                                                                <li class='save-and-add' data-toggle='modal' list_id='4' data-target1='#modal-add-contact'>
                                                                                    <a href='javascript:void(0);'>
                                                                                <i class='fa fa-plus fa-fw'>
                                                                                    </i> Agregar un suscriptor</a></li>  
                                                                                <li class='save-and-add' data-toggle='modal' list_id='4' data-target1='#modal-import-files'>
                                                                                    <a href='#'>
                                                                                        <i class='fa fa-download fa-fw'></i> Importar un archivo</a>
                                                                                        </li>                                        
                                                                                <li class='save-and-add' data-toggle='modal' list_id='4' data-target1='#modal-copy-paste-contacts'><a href='#'>
                                                                                <i class='fa fa-share fa-fw'></i> Copiar/Pegar suscriptores</a></li>                                        
                                                                                <li list_id='renombrarLista'  class='rename' data-toggle='modal' data-target='#ActualizarList' >
                                                                                    <a href='' id='".$value['id']."' >
                                                                                        <i class='fa fa-pencil fa-fw'></i> Renombrar
                                                                                    </a>
                                                                                </li>
                                                                                <li data-toggle='modal' data-target='#confimation_list' '>
                                                                                    <a href='javascript:void(0)' id='".$value['id']."' nombreLista='".$value['name']."' class='delete_list'>
                                                                                    <i class='fa fa-trash fa-fw'></i> Eliminar</a>
                                                                                </li> 
                                                                    </ul>                                
                                                                </div>                            
                                                            </td>                        
                                            </tr>";}
                                                    }
                                                        ?>
                                                    
                                                   
                                                </tbody>
                                            </table>
                                        </div>
                                </div>
                                <!-- end Listing -->

                                <div class="text-center">
                                    <div id="btn-view-more-wrap">
                                        <a href="javascript:void(0);" class="btn btn-default spacer-top-xs spacer-bottom-md" id="btn-view-more">Ver más</a>
                                    </div>
                                    <div id="loader-view-more"></div>
                                </div>

                            </div>
                            <!-- end .col -->

                        </div>
                        <!-- end .row -->

                    </div>
                    <!-- end #content -->
                    <div class="clearfix"></div>

                </div>
                <!-- end #main-content -->
            </div>
        <!-- end </row> --> 
    </div>
    </div>
</div>
</div>

<!-- Pop -->

 <!-- <ActualizarFolder> -->
<div class="modal fade modal-primary in" id="ActualizarFolder">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title"><span class="fa fa-plus"></span> Editar nombre de Carpeta<span id="updatelistLoader"></span></h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label for="listupdatename" class="sr-only">Nombre de la carpeta</label>
                    <input type="text" value="" data-target2="#modal-import-files" class="emailtext form-control" name="listupdatename" placeholder="Nombre de lista" id="listupdatename">
                </div>
                <div class="row">
                    <div class="col-sm-4" id="agregarCarpeta" style="left: 30%;">
                        <a  href="" data-toggle="modal"  data-target1="#modal-import-files" class="btn btn-primary btn-lg btn-block save-and-add" style="min-height:95px; padding:15% 0px;"><i class="fa fa-pencil-square-o"></i><br> <span style="white-space:pre-wrap;">Actualizar</span></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
 <!-- </ActualizarFolder> -->

 <!-- <nuevoFolder> -->

<div class="modal fade modal-primary in" id="nuevoFolder">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title"><span class="fa fa-plus"></span> Agregar una nueva Carpeta<span id="newlistLoader"></span></h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label for="folderaddname" class="sr-only">Nombre de la carpeta</label>
                    <input type="text" value="" data-target2="#modal-import-files" class="emailtext form-control" name="folderaddname" placeholder="Nombre de carpeta" id="folderddname">
                </div>
                <div class="row">
                    <div class="col-sm-4" id="nuevaCarpeta" style="left: 30%;">
                        <a  href="" data-toggle="modal"  onclick="this.href='/sendinblue/addFolder/0/'+document.getElementById('folderddname').value" data-target1="#modal-import-files" class="btn btn-primary btn-lg btn-block save-and-add" style="min-height:95px; padding:15% 0px;"><i class="fa fa-folder-open"></i><br> <span style="white-space:pre-wrap;">agregar</span></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
 <!-- </nuevoFolder> -->
 <!-- <confimation_modal> -->
<div class="modal fade modal-primary in" id="confimation_modal"  aria-hidden="false">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>          
                    <h4 id="myModalLabel" class="modal-title">Eliminar la carpeta</h4>          
                </div>          
                <div class="modal-body" id="nombreCarpeta"><p>¿Está seguro de que desea eliminar la carpeta <strong>Prueba 2</strong> y todas las listas incluidas?</p>          
                </div>          
                <div class="modal-footer">          
                    <a href="#" class="btn deleteall btn-primary" id="deleteList">Eliminar carpeta y todas sus listas</a>          
                    <a href="#" class="btn btn-default" data-dismiss="modal">Cancelar</a>            
                    <span id="lightbox_loader"></span>          
                </div>        
            </div>        
        </div>        
    </div>
 <!-- </confimation_modal> -->


 <!-- <nuevaLista> -->
<div class="modal fade modal-primary in" id="nuevaLista">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title"><span class="fa fa-plus"></span> Agregar nueva lista<span id="updatelistLoader"></span></h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label for="listaddname" class="sr-only">Nombre de la carpeta</label>
                    <input type="text" value="" data-target2="#modal-import-files" class="emailtext form-control" name="listaddname" placeholder="Nombre de lista" id="listaddname">
                </div>
                <div class="row">
                    <div class="col-sm-4" id="agregarLista" style="left: 30%;">
                        <a  href="" data-toggle="modal"  data-target1="#modal-import-files" class="btn btn-primary btn-lg btn-block save-and-add" style="min-height:95px; padding:15% 0px;"><i class="fa fa-list-ul"></i><br> <span style="white-space:pre-wrap;">Agregar</span></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
 <!-- </nuevaLista> -->


 <!-- <ActualizarList> -->
<div class="modal fade modal-primary in" id="ActualizarList">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title"><span class="fa fa-plus"></span> Editar nombre de Lista<span id="updatelistLoader"></span></h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label for="listaupdatename" class="sr-only">Nombre de la lista</label>
                    <input type="text" value="" data-target2="#modal-import-files" class="emailtext form-control" name="listaupdatename" placeholder="Nombre de lista" id="listaupdatename">
                </div>
                <div class="row">
                    <div class="col-sm-4" id="actualizarLista" identificador="" style="left: 30%;">
                        <a  href="" data-toggle="modal"  data-target1="#modal-import-files" class="btn btn-primary btn-lg btn-block save-and-add" style="min-height:95px; padding:15% 0px;"><i class="fa fa-pencil-square-o"></i><br> <span style="white-space:pre-wrap;">Actualizar</span></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
 <!-- </ActualizarList> -->
 <!-- <confimation_modal> -->
<div class="modal fade modal-primary in" id="confimation_list"  aria-hidden="false">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>          
                    <h4 id="myModalLabelList" class="modal-title">Eliminar la Lista</h4>          
                </div>          
                <div class="modal-body" id="cambiarNombreLista"><p>¿Está seguro de que desea eliminar la lista <strong>Prueba 2</strong> y todos sus contactos incluidas?</p>          
                </div>          
                <div class="modal-footer" identificador="" id="confElimLista"  >          
                    <a href="#" class="btn deleteall btn-primary" >Eliminar lista y todos sus contactos</a>          
                    <a href="#" class="btn btn-default" data-dismiss="modal">Cancelar</a>            
                    <span id="lightbox_loader"></span>          
                </div>        
            </div>        
        </div>        
    </div>
 <!-- </confimation_modal> -->
   
                
                  <?php                            
//                  <--------- Obtiene un array con todos las carpetas en sendinblue-------->
                                           /* var_dump($this->ListAllFolder); 
                                            echo "<br />";
                                            echo "<br />";
                                            foreach ($this->ListAllFolder['data']['folders'] as $key => $value)  
                                            {  
                                                echo $value['id'] . "<br />";
                                                 
                                                foreach ($value as $k => $v)  
                                                {  
                                                    echo $k. "|". $v ."<br/>";  
                                                }       
                                            }  
                                            echo "<br />";
                                            echo "<br />";*/
                                            
//                  <--------- Obtiene un array con los datos de una carpeta por su ID -------->                                            
/*
                                       

                                            var_dump($this->FolderDetails['data']); 
                                            echo "<br />";
                                            echo "<br />";
                                            $count = 0;
                                            foreach ($this->FolderDetails['data'] as $key => $value)  
                                            {  
                                                //echo $key ."|". $value . "<br />";
                                                 foreach ($value['lists'] as $k => $v)  
                                                {  
                                                    
                                                    foreach ($v as $t => $y)  
                                                    {  
                                                        echo $t ."|". $y . "<br />";
                                                    }  
                                                } 
                                                
                                            } 
                                            echo $count;
               */
           //<---------  listas de la carpeta por ID -----------> 
                                            /*var_dump($this->allLists)['data']; 
                                            echo "<br />";
                                            echo "<br />";
                                            $count = 0;
                                            foreach ($this->allLists['data']['lists'] as $key => $value)  
                                            {  
                                                //echo $key ."|". $value . "<br />";
                                                 foreach ($value as $k => $v)  
                                                {  
                                                    echo $k. "|". $v ."<br/>"; 
                                                } 
                                                
                                            } */
                                            
?> 
  
                   


 
