<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Reportes\Module'                        => __DIR__ . '/Module.php',
    'Reportes\Controller\IndexController' => __DIR__ . '/src/Reportes/Controller/IndexController.php',
    'Reportes\Framework\TestCase'        => __DIR__ . '/tests/ZendSkeletonModule/Framework/TestCase.php',
    'Reportes\SampleTest'                => __DIR__ . '/tests/Reportes/SampleTest.php',
);