<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Sendinblue\Module'                        => __DIR__ . '/Module.php',
    'Sendinblue\Controller\IndexController' => __DIR__ . '/src/Sendinblue/Controller/IndexController.php',
    'Sendinblue\Framework\TestCase'        => __DIR__ . '/tests/ZendSkeletonModule/Framework/TestCase.php',
    'Sendinblue\SampleTest'                => __DIR__ . '/tests/Sendinblue/SampleTest.php',
);