<script>
	(function() {
		$("#navbarCollapse ul li").each(function() {
			$(this).removeClass("active");
		});
		$("#navbarCollapse ul").children().eq(3).addClass("active");
		document.title = "Convocatoria - InflaRun";
	})();
</script>
<section id="fotoSuperiorFundacion">
	<div class="container-fluid">
		<div class="row" align="center">
			<img id="fotoSuperiorInnerFundacion" src="<?php echo $this -> basePath(); ?>/css/Imagenes/Convocatoria.png" />
		</div>
	</div>
</section>
<br>
<section id="bodyPreguntas">
	<div id="outerPreguntas" class="container-fluid">
		<div class="row">
			<div class="col-sm-12 text-justify">
				<dl>
					<dt class="text-primary">Convocatoria "Primera Carrera InflaRun Guanajuato 2016"</dt>
					<br>
					<dd>• Las inscripciones serán en nuestra página <a href="https://inflarun.mx" target="_blank">InflaRun</a>.</dd>
					<br>
					<dd>• Contaremos con pago en efectivo, tarjeta de crédito, débito y en las taquillas del Parque
					Guanajuato Bicentenario. Deberán guardar el comprobante para presentarlo en el momento de
					recoger su paquete de corredor.</dd>
					<br>
					<dd>• No habrá un máximo ni un mínimo de participantes por equipo.</dd>
					<br>
					<dd>• Si desean que todos los miembros del equipo participen en el mismo horario, una persona tendrá que registrar
					al equipo y realizar el pago por el total de las inscripciones. Una vez recibido el pago se les enviará un correo
					con una liga, el cual tendrá que ser reenviado a los demás miembros del equipo para que puedan registrarse a la carrera.
					<strong>No habrá cambios en inscripciones, ni de día ni de horario.</strong></dd>
					<br>
					<dd>• Los bloques de salida estarán limitados a 70 corredores. Si un bloque ya está lleno no se podrán registrar en ese
					horario. Por ejemplo, si quieren registrar a 20 personas en un bloque donde quedan menos de 20 lugares disponibles, se
					tendrá que seleccionar otro horario.</dd>
					<br>
					<dd>• Los acompañantes deben pagar la entrada que cobra el Parque Guanajuato Bicentenario, la cual corresponde a $25 adultos
					y $10 niños. Dicha entrada incluye todas las atracciones y exposiciones que el parque ofrece a sus visitantes.</dd>
					<br>
					<dd>• La entrega de paquetes de corredor será el mismo día en el que se hayan registrado. Tendrán que llegar por lo menos
					una hora antes del horario que escogieron para participar. Una vez que hayan recogido su paquete podrán dejar sus cosas en
					el guardarropa y dirigirse hacia los bloques de salida. Los participantes tendrán que estar ya integrados en su bloque de
					salida 10 minutos antes de su horario de arranque.</dd>
					<br>
					<dd>• Les pedimos atentamente que sean puntuales ya que así respetaremos la salida de otros participantes y por consiguiente
					la suya. Las personas que no salgan en el horario en el que se registraron perderán el derecho a participar. Al momento de
					inscribirse los participantes seleccionan el día y horario en el que desean participar; una vez registrados <strong>no habrá
					cambios</strong>. El paquete de corredor se entregará única y exclusivamente al corredor mostrando una <strong>identificación
					oficial</strong> y su <strong>comprobante de inscripción</strong></dd>
					<br>
					<dd>• La entrada al evento será por la <strong>Puerta 7</strong> del Parque Guanajuato Bicentenario, ubicado en Carretera de
					cuota Silao-Gto Km 3.8, Los Rodríguez, Silao, Guanajuato.</dd>
					<br>
					<dd>• Les sugerimos llegar por lo menos una hora antes del horario que seleccionaron para participar.</dd>
					<br>
					<dd>• La inscripción al evento incluye la carrera, playera de corredor, medalla de competidor e hidratación durante y después
					del recorrido.</dd>
					<br>
					<dd>• Contaremos con servicio de guardarropa gratuito.</dd>
					<br>
					<dd>• La carrera es solo para <strong>mayores de 18 años</strong> cumplidos al día del evento.</dd>
					<br>
					<dd>• Los participantes que sean sorprendidos haciendo un mal uso de los inflables serán retirados del evento.</dd>
					<br>
					<dd>• El recorrido solo se puede pasar por cada inflable una vez. No se podrá permanecer en un inflable, se tiene que continuar
					el recorrido. En dado caso de que alguien no quiera pasar por un inflable lo podrá rodear. El recorrido durará el tiempo que
					tardan los participantes en completar el circuito.</dd>
					<br>
					<dd>• El primer bloque de salida arranca a las 8:00 a.m. Las personas que se inscriban en ese horario tendrán que llegar a
					las 6:00 a.m. El último bloque de salida será a las 5:00 p.m. El evento termina a las 7:00 p.m.</dd>
				</dl>
			</div>
		</div>
		<br>
	</div>
</section>