<script>
	(function() {
		$("#navbarCollapse ul li").each(function() {
			$(this).removeClass("active");
		});
		$("#navbarCollapse ul").children().eq(3).addClass("active");
		document.title = "Convocatoria - InflaRun";
	})();
</script>
<section id="bodyPreguntas">
	<div id="outerPreguntas" class="container-fluid">
		<div class="row">
			<div class="col-sm-12 text-justify">
				<dl>
					<dt class="text-primary">Convocatoria</dt>
					<dd><strong>Las inscripciones inician el viernes 19 de agosto y cerrarán cuando se terminen
					los lugares disponibles.</strong></dd>
					<br>
					<dd>• No habrá un máximo ni mínimo de participantes por equipo.</dd>
					<dd>• Si desean que todos los miembros del equipo participen en el mismo horario, una persona
					tendrá que registrar el equipo y realizar el pago por el total de las inscripciones. Una vez
					recibido el pago se les proporcionará un código único de equipo, el cual los miembros utilizarán
					para registrarse. Esto garantizará que todos corran en el mismo horario. No habrá cambios en
					inscripciones, ni de día ni de horario.</dd>
					<br>
					<br>
					<dd>• Los bloques de salida estarán limitados a 50 corredores. Si un bloque ya está lleno no se
					podrán registrar en ese horario. Si quieren registrar por ejemplo a 20 personas en un bloque donde
					quedan menos de 20 lugares disponibles, se tendrá que seleccionar otro horario.</dd>
					<br>
					<br>
					<dd>• Los acompañantes y los niños no pagan entrada. Contaremos con un área infantil totalmente
					gratuita para que los pequeños se diviertan mientras los grandes corren siempre y cuando estén
					acompañados por un adulto responsable en todo momento. Nosotros proporcionaremos el área infantil,
					pero el cuidado de los pequeños es responsabilidad de sus acompañantes. Ningún niño podrá entrar al
					área infantil si no viene acompañado de un adulto.</dd>
					<br>
					<br>
					<dd>• La entrega de paquetes de corredor será el mismo día en el que se hayan registrado. Tendrán que
					llegar por lo menos una hora antes del horario que escogieron para participar. Una vez que hayan recogido
					su paquete podrán dejar sus cosas en el guardarropa y dirigirse hacia los bloques de salida. Los
					participantes tendrán que estar ya integrados en su bloque de salida 10 minutos antes de su horario de
					arranque. </dd>
					<dd>• Les pedimos atentamente que sean puntuales ya que así respetaremos la salida de otros participantes
					y por consiguiente la suya. Las personas que no salgan en el horario en el que se registraron perderán el
					derecho a participar. Al momento de inscribirse los participantes seleccionan el día y el horario en el
					que desean participar una vez registrados no habrá cambios. El paquete de corredor se le entregará única
					y exclusivamente al participante mostrando una identificación oficial y su registro de participación.</dd>
					<br>
					<br>
					<dd>• La entrada al evento será por el Centro Banamex ubicado sobre Avenida Del Conscripto 311. Les
					sugerimos llegar por lo menos una hora antes del horario que seleccionaron para participar.</dd>
					<dd>• La inscripción al evento incluye la carrera, playera de corredor, medalla de competidor, hidratación
					durante y después del recorrido. </dd>
					<dd>• Contaremos con servicio de guardarropa.</dd>
					<br>
					<br>
					<dd>• Las inscripciones serán en nuestra página www.inflarun.mx Para pagos en efectivo se les generará un
					código, el cual podrán utilizar para pagar en Oxxo, Seven Eleven, Extra, Farmacias Benavides y algunos
					puntos más. Deberán guardar el comprobante para presentarlo en el momento de recoger su paquete de corredor.</dd>
					<dd>• La carrera es sólo para mayores de 18 años cumplidos al día del evento.</dd>
					<br>
					<dd>• Los participantes que sean sorprendidos haciendo un mal uso de los inflables serán retirados del
					evento.</dd>
					<br>
					<dd>• El recorrido consta de aproximadamente 5 kilómetros con 10 obstáculos inflables. Sólo se puede
					pasar por cada inflable una vez. No se podrá permanecer en un inflable, se tiene que continuar el recorrido.
					En dado caso de que alguien no quiera pasar por un inflable lo podrá rodear. El recorrido durará el tiempo que tardan los participantes en completar el circuito.</dd>
					<br>
					<dd>• El primer bloque de salida arranca a las 7 a.m. Las personas que se inscriban en ese horario tendrán
					que llegar a las 6a.m. El último bloque de salida será a las 5:30 p.m. El evento termina a las 7 p.m.</dd>
				</dl>
			</div>
		</div>
		<br>
	</div>
</section>