<script src="https://connect.facebook.net/es_LA/sdk.js" id="facebook-jssdk"></script>
<script>
	(function() {
		// Carga de Facebook.
		FB.init({
			appId: "1783216848631932",
			xfbml: true,
			version: "v2.6"
		});
	})();
</script>
<script>
	(function() {
		$("#navbarCollapse ul li").each(function() {
			$(this).removeClass("active");
		});
		$("#navbarCollapse ul").children().eq(2).addClass("active");
		document.title = "Fundación - InflaRun";
	})();
</script>
<section id="carrera">
	<div id="carouselCarrera" class="container-fluid">
		<div class="row" align="center">
			<div id="carouselCarreraSlide" class="carousel slide" data-ride="carousel" data-interval="4000">
				<div id="carouselCarreraInterior" class="carousel-inner" role="listbox">
					<div class="item active">
						<div class="slider-size">
							<img src="<?php echo $this -> basePath(); ?>/css/Imagenes/Fundacion2.png" style="height: 100%; width: 100%" />
						</div>
					</div>
					<div class="item">
						<div class="slider-size">
							<img src="<?php echo $this -> basePath(); ?>/css/Imagenes/banner-fundacion.png" style="height: 100%; width: 100%" />
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<br>
<div id="bodyFundacion">
	<section id="introduccionFundacion">
		<div class="container-fluid">
			<div class="row">
				<div class="col-md-8">
					<div class="row">
						<div id="introFundacion" class="col-sm-9 text-justify">
							<br>
							<p>A principios de 2015 llega a México la empresa "INFLA RUN®". Un nuevo concepto de carreras deportivas en
							nuestro país con un estilo muy propio, donde miles de personas se darán cita para completar una serie de
							trayectos increíbles y llenos de diversión, al brincar sobre inflables gigantes que serán del agrado de chicos
							y grandes.</p>
							<br>
							<p>CHOCHO® INFLARUN es un proyecto que nace del amor hacia los niños con cáncer, donde la ayuda, el
							deporte y la integración familiar se unirán año tras año, para lograr convertir nuestro país en un
							México más involucrado en la ayuda del prójimo.</p>
							<h3><strong>Nuestra Alianza Social</strong></h3>
							<p>En marzo de 2016 los directivos de "INFLA RUN®", como Empresa Socialmente Responsable, y Fundación
							CHOCHO® unen sus esfuerzos y su experiencia para iniciar una gira a nivel nacional de carreras con
							causa en apoyo a los niños y niñas con cáncer.</p>
							<h3><strong>Nuestro Objetivo Social</strong></h3>
							<p>Reunir el mayor número de corredores con causa en todo México, para poder crear fondos y así ayudar
							a las familias de los niños y niñas en las necesidades básicas como transporte, hospedaje y alimentos.</p>
							<br>
							<p>Nuestro proyecto contempla la integración y el apoyo en todo momento para las familias de los niños
							con cáncer. Por ello, hemos adoptado un concepto donde el 100% de nuestros voluntarios que estarán en
							nuestros eventos serán los mismo familiares de los pacientes (mamá y papá), para que ellos puedan
							recibir un incentivo en efectivo por su ayuda, y además que puedan vender sus pájaros CHOCHO® en
							todas nuestras carreras mientras trabajan.</p>
							<br>
						</div>
					</div>
				</div>
				<div id="foto2ParentFundacion" class="col-md-3" align="left">
					<img id="chochoAmarilloFundacion" src="<?php echo $this -> basePath(); ?>/css/Imagenes/Fundacion.png" />
					<img id="foto2Fundacion" src="<?php echo $this -> basePath(); ?>/css/Imagenes/foto2_fundacion.png" />
					<br>
					<br>
					<br>
					<div class="fb-page" data-href="https://www.facebook.com/FundacionChocho" data-tabs="timeline" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true">
						<blockquote cite="https://www.facebook.com/FundacionChocho" class="fb-xfbml-parse-ignore">
							<a href="https://www.facebook.com/FundacionChocho">Fundación Chocho</a>
						</blockquote>
					</div>
				</div>
			</div>
		</div>
	</section>
	<br>
	<br>
	<footer id="footerFundacion" class="footer">
		<div id="footerInnerFundacion" align="center" class="container">
			<h3><strong><a href="http://www.elmundodechocho.org/" target="_blank">Fundación CHOCHO® A.C.</a></strong></h3>
			<h4><strong>Av. Insurgentes Sur No. 3700-C, C.P. 04530, Col. Insurgentes Cuicuilco, Del. Coyoacán, Ciudad de México</strong></h4>
			<br>
			<br>
		</div>
	</footer>
</div>
