<script>
	(function() {
		$("#navbarCollapse ul li").each(function() {
			$(this).removeClass("active");
		});
		$("#navbarCollapse ul").children().eq(4).addClass("active");
		document.title = "Preguntas Frecuentes - InflaRun";
	})();
</script>
<section id="fotoSuperiorPreguntas">
	<div class="container-fluid">
		<div class="row" align="center">
			<img id="fotoSuperiorInnerPreguntas" src="<?php echo $this -> basePath(); ?>/css/Imagenes/queesinflarunbanner.png" />
		</div>
	</div>
</section>
<br>
<section id="bodyPreguntas">
	<div id="outerPreguntas" class="container-fluid">
		<div class="row">
			<div class="col-sm-12 text-justify">
				<dl>
					<dt class="text-primary">¿Qué es InflaRun?</dt>
					<dd><strong>InflaRun</strong> es la primera carrera en México de 5 kilómetros con 10 obstáculos inflables donde puedes
					retar al niño que llevas dentro.</dd>
					<br>
					<dt class="text-primary">¿Dónde me inscribo?</dt>
					<dd>Las inscripciones son en nuestra página <a href="<?php echo $this -> basePath(); ?>">InflaRun</a>.</dd>
					<br>
					<dt class="text-primary">¿Cómo puedo pagar?</dt>
					<dd>Contamos con pago con tarjeta de crédito, débito y pago en efectivo en Oxxo, Seven Eleven, Extra, Chedraui y
					Farmacias Benavides.</dd>
					<br>
					<dt class="text-primary">¿Cuál es el horario de la carrera?</dt>
					<dd>Al ser una carrera con obstáculos, los participantes saldrán en bloques de 40 personas cada 10 minutos, esto con el fin
					de que disfruten la experiencia al máximo. El primer arranque será a las 7am y el último a las 5pm. Es necesario que sean
					puntuales, ya que la organización respetará los horarios en los que se inscriban.</dd>
					<br>
					<dt class="text-primary">¿Qué incluye la inscripción?</dt>
					<dd>El costo incluye la inscripción a la carrera, playera de corredor, medalla de competidor y algunas sorpresas más.</dd>
					<br>
					<dt class="text-primary">¿Debo correr en equipo?</dt>
					<dd>No. Individual o en equipo, pueden vivir una experiencia única con divertidos retos.</dd>
					<br>
					<dt class="text-primary">¿De cuántas personas tiene que ser el equipo?</dt>
					<dd>No hay un número mínimo ni máximo de corredores por equipo.</dd>
					<br>
					<dt class="text-primary">¿Hay algún precio especial por equipo?</dt>
					<dd>No. El costo es individual sin importar de cuantas personas sea el equipo.</dd>
					<br>
					<dt class="text-primary">¿Por qué son dos días de carrera?</dt>
					<dd>Son dos días de carrera para que escojan el que mejor les quede para correr.</dd>
					<br>
					<dt class="text-primary">¿Pueden participar niños?</dt>
					<dd>No. La carrera es solo para mayores de 18 años cumplidos al día del evento. Contaremos con un área de inflables
					infantiles para que los pequeños se diviertan mientras los grandes corren.</dd>
					<br>
					<dt class="text-primary">¿El área infantil tendrá algún costo?</dt>
					<dd>No, el área inflantil será totalmente gratuita.</dd>
					<br>
					<dt class="text-primary">¿Cómo funciona el área infantil?</dt>
					<dd>Los niños que acompañen a los corredores podrán hacer uso del área infantil bajo la supervisión de un adulto responsable
					que los acompañe. InflaRun solo proporcionará los juegos; el cuidado de los niños es responsabilidad única y exclusivamente
					del adulto que los esté supervisando.</dd>
					<br>
					<dt class="text-primary">¿Acompañantes y niños pagan entrada?</dt>
					<dd>La entrada para acompañantes y niños es gratis.</dd>
				</dl>
			</div>
		</div>
		<br>
	</div>
</section>