<script>
	(function() {
		$("#navbarCollapse ul li").each(function() {
			$(this).removeClass("active");
		});
		$("#navbarCollapse ul").children().eq(2).addClass("active");
		document.title = "Prensa - InflaRun";
	})();
</script>
<div id="bodyFundacion">
	<div class="container">
		<div class="col-sm-12 text-justify">
			<hr>
			<div class="row">
				<div class="col-sm-4 col-xs-5">
					<img src="<?php echo $this -> basePath(); ?>/css/Imagenes/prensa/inflarun-prensa-1.jpg" height="80%" width="95%" />
				</div>
				<div class="col-sm-8 col-xs-7">
					<h3 class="text-info">
						<a href="http://www.chilango.com/general/infla-run-la-primera-carrera-de-obstaculos-inflables-en-la-ciudad/" target="_blank">
							InflaRun, la primera carrera de obstáculos inflables en la ciudad
						</a>
						<br>
						<small>www.chilango.com</small>
					</h3>
					<p>
						¡En esta carrera, los niños están vetados! pues necesitas ser mayor de edad para inscribirte a la primera
						prueba de inflables en la ciudad de México.
					</p>
				</div>
			</div>
			<hr>
			<div class="row">
				<div class="col-sm-4 col-xs-5">
					<img src="<?php echo $this -> basePath(); ?>/css/Imagenes/prensa/inflarun-prensa-2.jpg" height="80%" width="95%" />
				</div>
				<div class="col-sm-8 col-xs-7">
					<h3 class="text-info">
						<a href="https://www.soycorredora.com/razones-correr-inflarun/" target="_blank">
							InflaRun, las 10 razones para correrla
						</a>
						<br>
						<small>www.soycorredora.com</small>
					</h3>
					<p>
						InflaRun es una carrera de 5 kilómetros con 10 obstáculos inflables, en donde puedes participar de forma
						individual o en equipo y el objetivo es que la disfrutes.
					</p>
				</div>
			</div>
			<hr>
			<div class="row">
				<div class="col-sm-4 col-xs-5">
					<img src="<?php echo $this -> basePath(); ?>/css/Imagenes/prensa/inflarun-prensa-3.jpg" height="80%" width="95%" />
				</div>
				<div class="col-sm-8 col-xs-7">
					<h3 class="text-info">
						<a href="https://www.timeoutmexico.mx/df/que-hacer/carrera-inflarun" target="_blank">
							Carrera InflaRun
						</a>
						<br>
						<small>www.timeoutmexico.mx</small>
					</h3>
					<p>
						El sueño de tu infancia se hace realidad: ¡una carrera de inflables! Recorre 5 km con 10 obstáculos inflables
						de muchos tamaños y formas -desde uno con pelotas gigantes hasta un avión de más de 8 metros de altura- para
						que trepes, deslices o brinques en ellos. Aquí no importa si eres el más rápido, gana el que se divierta más.						
					</p>
				</div>
			</div>
			<hr>
			<div class="row">
				<div class="col-sm-4 col-xs-5">
					<img src="<?php echo $this -> basePath(); ?>/css/Imagenes/prensa/inflarun-prensa-4.jpg" height="80%" width="95%" />
				</div>
				<div class="col-sm-8 col-xs-7">
					<h3 class="text-info">
						<a href="https://www.dondeir.com/2016/08/carrera-con-obstaculos-inflables-inflarun/" target="_blank">
							Carrera con obstáculos inflables InflaRun
						</a>
						<br>
						<small>www.dondeir.com</small>
					</h3>
					<p>
						Corre por en medio de pelotas gigantes, trepa un inflable en forma de avión de más de 8 metros de altura,
						y sigue corriendo. Deslizate en una resbaladilla,  pasa corriendo sobre un colchón lleno de agujeros y
						rebota como enano en los inflables. Esta carrera “InflaRun” es de 5km y se compone de 10 obstáculos,
						habrá inflables de todos los tamaños.
					</p>
				</div>
			</div>
			<hr>
		</div>
	</div>
</div>