<script>
	(function() {
		$("#navbarCollapse ul li").each(function() {
			$(this).removeClass("active");
		});
		$("#navbarCollapse ul").children().eq(1).addClass("active");
		document.title = "¿Qué es? - InflaRun";
	})();
</script>
<section id="carrera">
	<div id="carouselCarrera" class="container-fluid">
		<div class="row">
			<div id="carouselCarreraSlide" class="carousel slide" data-ride="carousel" data-interval="4000">
				<div id="carouselCarreraInterior" class="carousel-inner" role="listbox">
					<div class="item active">
						<div class="slider-size">
							<img src="<?php echo $this -> basePath(); ?>/css/Imagenes/queesinflarunnuevo.png" style="height: 100%; width: 100%" />
						</div>
					</div>
					<div class="item">
						<div class="slider-size">
							<img src="<?php echo $this -> basePath(); ?>/css/Imagenes/QUEES.png" style="height: 100%; width: 100%" />
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<br>
<section id="introduccionFundacion">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-8">
				<div class="row">
					<div id="introFundacion" class="col-sm-9 text-justify">
						<br>
						<p><strong>InflaRun</strong> es la primera carrera en México de 5 kilómetros con 10 obstáculos inflables.
						Individual o en equipo, pueden vivir una experiencia única con divertidos retos. Aquí no importa si eres
						el más rápido o fuerte, todos pueden disfrutarla.</p>
						<br>
						<p>Tenemos inflables de todos los tamaños, desde un colchón con agujeros donde tienes que pasar corriendo,
						hasta un avión de más de 8 metros de altura. Algunos con resbaladillas, otros son para rebotar e incluso
						para pasar por en medio de pelotas gigantes.</p>
						<br>
						<p>El recorrido será en el infield del Hipódromo de las Américas los días 24 y 25 de septiembre.
						Al ser una carrera con obstáculos, los participantes saldrán en bloques de 40 personas cada 10 minutos, esto
						con el fin de que disfruten la experiencia al máximo. El primer arranque será a las 7 am y el último a las
						5 pm.</p>
						<br>
						<p>La carrera es para mayores de <strong>18 años</strong>. Contaremos con un área de inflables infantiles
						para que los pequeños se diviertan mientras los grandes corren. No existe un número mínimo ni máximo de
						participantes por equipo.</p>
						<br>
						<p>El costo es de $580 por persona e incluye la inscripción de la carrera, playera de corredor, medalla de
						competidor y algunas sorpresas más. Tendremos una zona de Food Trucks, así como de merchandising y
						activaciones.</p>
						<br>
						<p>InflaRun es una carrera con causa que en conjunto con la fundación "El Mundo de Chocho" apoyará a niños
						con cáncer, logrando convertir nuestro país en un México más involucrado en la ayuda a nuestros niños.</p>
						<br>
						<p>Las inscripciones abrirán en agosto y se podrán realizar en nuestra página 
						<a href="<?php echo $this -> basePath(); ?>">InflaRun</a> en donde contaremos con pagos con tarjeta de
						crédito o débito y pagos en Oxxo.</p>
						<br>
						<p>Próxima sede: Guanajuato. Estaremos publicando más fechas alrededor de la
						República Mexicana muy pronto.</p>
					</div>
				</div>
			</div>
			<div id="foto2ParentFundacion" class="col-md-3" align="left">
				<img id="chochoAmarilloFundacion" src="<?php echo $this -> basePath(); ?>/css/Imagenes/Secciones/queesinflarun1.png" />
				<img id="foto2Fundacion" src="<?php echo $this -> basePath(); ?>/css/Imagenes/Secciones/queesinflarun2.png" />
				<br>
				<br>
				<br>
				<div class="fb-page" data-href="https://www.facebook.com/inflarun" data-tabs="timeline" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true">
					<blockquote cite="https://www.facebook.com/inflarun" class="fb-xfbml-parse-ignore">
						<a href="https://www.facebook.com/inflarun">InflaRun</a>
					</blockquote>
				</div>
			</div>
		</div>
		<br>
	</div>
</section>
