<script>
	(function() {
		$("#navbarCollapse ul li").each(function() {
			$(this).removeClass("active");
		});
		$("#navbarCollapse ul").children().eq(3).addClass("active");
		document.title = "Ruta - InflaRun";
	})();
</script>
<section id="fotoSuperiorRuta">
	<div class="container-fluid">
		<div class="row" align="center">
			<img id="fotoSuperiorInnerRuta" src="<?php echo $this -> basePath(); ?>/css/Imagenes/primer-carrera.png" />
		</div>
	</div>
</section>
<div align="center">
	<h1>¡En construcción!</h1>
</div>