<?php
	$pagos = $this -> pagos;
	$hayPagos = !empty($pagos);
?>
<script>
	(function() {
		$("#navbarCollapse ul li").each(function() {
			$(this).removeClass("active");
		});
		$("#navbarCollapse ul").children().last().addClass("active");
		document.title = "Admin Main - InflaRun";
	})();
</script>
<div id="cuentaBody" class="container-fluid">
	<div class="row">
		<h1>Bienvenido, Administrador.</h1>
		<br>
		<div class="col-sm-2 col-xs-6">
			<div class="dropdown">
				<button class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
					Opciones
					<span class="caret"></span>
				</button>
				<ul class="dropdown-menu">
					<li><a href="<?php echo $this -> basePath(); ?>/application/cuenta/adminusuarios">Usuarios</a></li>
					<li><a href="<?php echo $this -> basePath(); ?>/application/cuenta/adminregistromanual">Registro Manual</a></li>
					<li><a href="<?php echo $this -> basePath(); ?>/application/cuenta/adminlogout">Cerrar Sesión</a></li>
				</ul>
			</div>
		</div>
		<div class="col-sm-2 col-xs-6">
			<a href="<?php echo $this -> basePath(); ?>/application/cuenta/adminmain" class="btn btn-warning">Actualizar</a>
		</div>
	</div>
	<br>
	<br>
	<div class="row">
		<div class="col-sm-12 col-xs-12">
			<h2>Pagos en Efectivo</h2>
			<div class="table-responsive">
				<table class="table table-striped">
					<thead>
						<tr>
							<th>Correo</th>
							<th>Nombre</th>
							<th>Orden ID</th>
							<th>Transacción</th>
							<th>Fecha de expiración</th>
							<th>Acción</th>
						</tr>
					</thead>
					<tbody>
						<?php if ($hayPagos): ?>
							<?php foreach ($pagos as $pago): ?>
								<tr>
									<td><?php echo $pago["correo"]; ?></td>
									<td><?php echo $pago["nombre"]; ?></td>
									<td><?php echo $pago["orderId"]; ?></td>
									<td><?php echo $pago["transaccion"]; ?></td>
									<td><?php echo $pago["fechaExpiracion"] ?></td>
									<td>
										<a href="<?php echo $this -> basePath(); ?>/application/cuenta/adminaceptarpago?idPago=<?php echo $pago["idPago"]; ?>" class="btn btn-success">Aceptar</a>
										<a href="<?php echo $this -> basePath(); ?>/application/cuenta/adminrechazarpago?idPago=<?php echo $pago["idPago"]; ?>" class="btn btn-danger">Rechazar</a>
									</td>
								</tr>
							<?php endforeach; ?>
						<?php endif; ?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<br>
</div>