<?php
	$session = new \Zend\Session\Container("admin");
	
	try {
		$dao = new \Application\Model\Dao\EquipoDao();
		$eventos = $dao -> consultaGenerica("SELECT * FROM DetallesEvento");
	} catch (Exception $ex) {
		$eventos = array();
	}
?>
<script>
	(function() {
		$("#navbarCollapse ul li").each(function() {
			$(this).removeClass("active");
		});
		$("#navbarCollapse ul").children().last().addClass("active");
		document.title = "Admin Cambiar Horario - InflaRun";
	})();
	
	function rellenarCampos(inscripcion, cambioHorario) {
		$("#nombre").val(inscripcion.nombre);
		$("#correo2").val(inscripcion.correo);
		$("#equipo").val(inscripcion.equipo);
		$("#noIntegrantes").val(inscripcion.noIntegrantes);
		$("#codigoCanje").val(inscripcion.codigoCanje);
		$("#noCorredor").val(inscripcion.noCorredor);
		$("#folio").val(inscripcion.folio);
		$("#fecha").val(inscripcion.fecha);
		$("#bloque").val(inscripcion.bloque);
		$("#idEquipo").val(inscripcion.idEquipo);
		
		inscripcion.integrantes.forEach(function(e) {
			var nombre = "<li class='list-group-item'><strong>Nombre:</strong> " + e.nombre + " " + e.paterno;
			var correo = " | <strong>Correo:</strong> "
				+ e.correo
				+ " <button id='"
				+ e.correo + "|" + $("#idDetallesEvento").val()
				+ "' class='btn btn-success btn-sm btn-reenviar-correo'>Reenviar Correo</button></li>";

			$("#integrantes").append(nombre + correo);
		});
		
		cambioHorario.dias.forEach(function(e) {
			var option = "<option value='" + e.idDiaEvento + "'>"
				+ e.fechaRealizacion + "</option>";
			$("#dia").append(option);
		});
		
		cambioHorario.dias[0].hit.forEach(function(e) {
			var option = "<option value='" + e.idDiaHit + "'>"
				+ e.horario + "</option>";
			$("#hit").append(option);
		});
		
		$("#dia").change(function() {
			var id = $(this).val();
			$("#hit").empty();

			var bloqueNuevo = cambioHorario.dias.filter(function(e) {
				return e.idDiaEvento == id;
			})[0];
			
			bloqueNuevo.hit.forEach(function(e) {
				var option = 
					"<option value='" + e.idDiaHit + "'>\n\
						" + e.horario + "</option>";
				$("#hit").append(option);
			});
		});
	}
	
	$(document).ready(function() {
		$("#btnBuscar").click(function() {
			var message;	
			$(".alert").remove();
			$("#formulario input[type='submit']").remove();
			$("#integrantes").empty();
			$("#btnBuscar").prop("disabled", true);
			$("#bodyPanel").prepend("\
				<div class='progress'>\n\
					<div class='progress-bar progress-bar-striped active' aria-valuenow='100' aria-valuemin='0' aria-valuemax='100' style='width: 100%'>\n\
						Estamos buscando en el sistema. ¡Solo un momento!\n\
					</div>\n\
				</div>"
			);
			
			$.get("<?php echo $this -> basePath(); ?>/application/cuenta/admincambiarhorariogetinfo", {
				correo: $("#correo").val(),
				idDetallesEvento: $("#idDetallesEvento").val()
			}, function(response) {
				if (response.estatus != 0) {
					message = 
						"<div class='alert alert-warning fade in'>\n\
							<a href='#' class='close' data-dismiss='alert' aria-label='close'>&times;</a>\n\
							<strong>" + response.message + "</strong>\n\
						</div>";
					$("#bodyPanel").prepend(message);
					$("#bodyPanel input[type='text']").val("");
					$("input[type='hidden']").val("");
					$("#bodyPanel input[type='text']").prop("disabled", true);
					$("#formulario select").prop("disabled", true);
					$("#formulario select").empty();
					$("#integrantes").empty();
				} else {
					rellenarCampos(response.inscripcion, response.cambioHorario);
					$("#formulario select").prop("disabled", false);
					$("#formulario").append("<input type='submit' value='Cambiar Horario' class='btn btn-info' />");
				}
				
				$(".progress").remove();
				$("#btnBuscar").prop("disabled", false);
			});
		});
		
		$("#integrantes").on("click", ".btn-reenviar-correo", function() {
			$("#integrantesPanel .alert").remove();
			$("#integrantesPanel").prepend("\
				<div class='progress'>\n\
					<div class='progress-bar progress-bar-striped active' aria-valuenow='100' aria-valuemin='0' aria-valuemax='100' style='width: 100%'>\n\
						Estamos reenviando el correo. ¡Solo un momento!\n\
					</div>\n\
				</div>"
			);
			$(this).prop("disabled", true);
			var button = $(this);
			var id = button.attr("id");
			var correo = id.split("|")[0];
			var idDetallesEvento = id.split("|")[1];
			var message;
			
			$.get("<?php echo $this -> basePath(); ?>/application/cuenta/adminusuariosreenviarcorreoajax", {
				correo: correo,
				idDetallesEvento: idDetallesEvento
			}, function(response) {
				if (response.estatus != 0) {
					message = 
						"<div class='alert alert-warning fade in'>\n\
							<a href='#' class='close' data-dismiss='alert' aria-label='close'>&times;</a>\n\
							" + response.message + "\n\
						</div>";
					$("integrantesPanel").prepend(message);
					button.prop("disabled", false);
				} else {
					message = 
						"<div class='alert alert-success fade in'>\n\
							<a href='#' class='close' data-dismiss='alert' aria-label='close'>&times;</a>\n\
							" + response.message + "\n\
						</div>";
				}
				
				$("#integrantesPanel .progress").remove();
				$("#integrantesPanel").prepend(message);
			});
		});
	});
</script>
<div id="cuentaBody" class="container-fluid">
	<div class="row">
		<h2>Cambiar Horario</h2>
		<br>
		<?php if ($session -> offsetExists("message")): ?>
			<div class="alert alert-info fade in">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<?php
					echo $session -> offsetGet("message");
					$session -> offsetUnset("message");
				?>
			</div>
		<?php endif; ?>
		<div class="col-md-2 col-xs-3">
			<div class="dropdown">
				<button class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
					Opciones
					<span class="caret"></span>
				</button>
				<ul class="dropdown-menu">
					<li class="dropdown-header">Usuarios</li>
					<li><a href="<?php echo $this -> basePath(); ?>/application/cuenta/adminusuarios">Administración de Usuarios</a></li>
					<li><a href="<?php echo $this -> basePath(); ?>/application/cuenta/adminmoduser">Modificar Info Usuario</a></li>
					<li class="divider"></li>
					<li class="dropdown-header">Administrador</li>
					<li><a href="<?php echo $this -> basePath(); ?>/application/cuenta/adminmain">Página Principal</a></li>
					<li><a href="<?php echo $this -> basePath(); ?>/application/cuenta/adminregistromanual">Registro Manual</a></li>
					<li><a href="<?php echo $this -> basePath(); ?>/application/cuenta/adminlogout">Cerrar Sesión</a></li>
				</ul>
			</div>
			<br>
			<br>
			<div class="form-group">
				<label>Busca por correo:</label>
				<input type="text" class="form-control" id="correo" />
				<br>
				<label>Evento</label>
				<select id="idDetallesEvento" class="form-control">
					<?php foreach($eventos as $evento): ?>
						<option value="<?php echo $evento["idDetallesEvento"]; ?>">
							<?php echo $evento["nombre"]; ?>
						</option>
					<?php endforeach; ?>
				</select>
				<br>
				<button id="btnBuscar" class="btn btn-default btn-block">Buscar</button>
			</div>
		</div>
		<div class="col-md-10 col-xs-9">
			<div class="panel panel-success">
				<div class="panel-heading">
					<strong>Información de Inscripción</strong>
				</div>
				<div id="bodyPanel" class="panel-body">
					<div class="col-md-6">
						<div class="form-group">
							<label>Nombre:</label>
							<input type="text" class="form-control" id="nombre" disabled />
						</div>
						<div class="form-group">
							<label>Correo:</label>
							<input type="text" class="form-control" id="correo2" disabled />
						</div>
						<div class="form-group">
							<label>Equipo:</label>
							<input type="text" class="form-control" id="equipo" disabled />
						</div>
						<div class="form-group">
							<label>Número de integrantes:</label>
							<input type="text" class="form-control" id="noIntegrantes" disabled />
						</div>
						<div class="form-group">
							<label>Código de canje:</label>
							<input type="text" class="form-control" id="codigoCanje" disabled />
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group">
							<label>No. de Corredor:</label>
							<input type="text" class="form-control" id="noCorredor" disabled />
						</div>
						<div class="form-group">
							<label>Folio:</label>
							<input type="text" class="form-control" id="folio" disabled />
						</div>
						<div class="form-group">
							<label>Fecha:</label>
							<input type="text" class="form-control" id="fecha" disabled />
						</div>
						<div class="form-group">
							<label>Bloque:</label>
							<input type="text" class="form-control" id="bloque" disabled />
						</div>
					</div>
					<br>
				</div>
				<div class="panel panel-danger">
					<div class="panel-heading">
						<strong>Cambio de Horario</strong>
					</div>
					<div class="panel-body">
						<div class="col-md-12">
							<strong>Cambiar a:</strong>
							<form id="formulario" action="<?php echo $this -> basePath(); ?>/application/cuenta/admincambiarhorariopost" method="post">
								<input type="hidden" id="idEquipo" name="idEquipo" />
								<div class="col-md-6">
									<div class="form-group">
										<label>Día:</label>
										<select id="dia" name="dia" class="form-control" disabled></select>
									</div>
								</div>
								<div class="col-md-6">
									<div class="form-group">
										<label>Bloque:</label>
										<select id="hit" name="hit" class="form-control" disabled></select>
									</div>
								</div>
								<br>
							</form>
						</div>
					</div>
				</div>
				<div class="panel panel-info">
					<div class="panel-heading">
						<strong>Integrantes del Equipo</strong>
					</div>
					<div id="integrantesPanel" class="panel-body">
						<div class="col-md-12">
							<ul id="integrantes" class="list-group"></ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<br>
</div>