<script>
	(function() {
		$("#navbarCollapse ul li").each(function() {
			$(this).removeClass("active");
		});
		$("#navbarCollapse ul").children().last().addClass("active");
		document.title = "Admin Login - InflaRun";
	})();
</script>
<div id="cuentaBody" class="container-fluid">
	<div class="row">
		<div class="col-sm-12">
			<h1>Admin Login</h1>
			<div class="panel panel-info">
				<div class="panel-heading">
					Por favor, ingresa tus credenciales.
				</div>
				<div class="panel-body">
					<div class="col-sm-12">
						<?php if (isset($this -> Error)): ?>
							<div class="alert alert-danger fade in">
								<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
								<?php echo $this -> Error; ?>
							</div>
						<?php endif; ?>
						<form action="<?php echo $this -> basePath(); ?>/application/cuenta/adminlogin" method="post">
							<div class="form-group">
								<label>Contraseña:</label>
								<input type="password" id="pwdLogin" name="pwdLogin" class="form-control" />
							</div>
							<input type="submit" value="Entrar" class="btn btn-info" />
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>