<?php
	$session = new \Zend\Session\Container("usuario");
	$inscripcionDetalles = $session -> offsetGet("inscripcionDetalles");
	$modalidad = $session -> offsetGet("modalidad");
	$diaHit = $session -> offsetGet("diaHit");
	
	if ($session -> offsetExists("metodoPago"))
		$metodoPago = $session -> offsetGet("metodoPago");
	
	if ($session -> offsetExists("datosBancarios"))
		$datosBancarios = $session -> offsetGet("datosBancarios");
	
	if ($session -> offsetExists("equipoCodigo"))
		$equipoCodigo = $session -> offsetGet("equipoCodigo");
	
	$nombreEvento = "{$inscripcionDetalles["evento"]["nombre"]} - {$inscripcionDetalles["detallesEvento"] -> getNombre()}";
	$estado = $inscripcionDetalles["estado"];
	$precio = $inscripcionDetalles["detallesEvento"]
		-> getPrecio() * ($modalidad["rdbModalidad"] === "equipo" ? (int)$modalidad["noIntegrantes"] : 1);
?>
<script>
	(function() {
		$("#navbarCollapse ul li").each(function() {
			$(this).removeClass("active");
		});
		$("#navbarCollapse ul").children().last().addClass("active");
		$("#navbarCollapse ul li a").children().last().html("Inscripciones");
		$("#navbarCollapse ul li").children().last().attr("href", "<?php echo $this -> basePath(); ?>/application/cuenta/index");
		document.title = "Confirmar Datos - InflaRun";
	})();
</script>
<div id="cuentaBody" class="container-fluid">
	<div class="row">
		<div class="col-md-7 col-xs-7">
			<div class="panel panel-success">
				<div class="panel-heading">
					<strong>Verifica que tus datos sean correctos</strong>
				</div>
				<div class="panel-body">
					<div class="col-md-12">
						<?php if(isset($this -> Error)): ?>
							<div class="alert alert-danger fade in">
								<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
								<?php echo $this -> Error["message"]; ?>
							</div>
							<br>
							<a href="<?php echo $this -> basePath(); ?>/application/cuenta/elegirbloque" class="btn btn-warning">Regresar a elección de bloques</a>
						<?php else: ?>
							<div class="list-group">
								<a class="list-group-item"><strong>Evento:</strong> <?php echo $nombreEvento; ?></a>
								<div class="panel panel-info">
									<div class="panel-heading">
										Modalidad:
										<?php if ($modalidad["rdbModalidad"] === "individual"): ?>
											Individual
										<?php elseif ($modalidad["rdbModalidad"] === "equipo"): ?>
											Equipo
										<?php else: ?>
											Código Canjeado
										<?php endif; ?>
									</div>
									<div class="panel-body">
										<div class="col-md-12">
											<div class="list-group">
												<?php if ($modalidad["rdbModalidad"] === "equipo"): ?>
													<a class="list-group-item">
														<strong>Nombre:</strong> <?php echo $modalidad["nombreEquipo"]; ?>
													</a>
													<a class="list-group-item">
														<strong>Integrantes: </strong> <?php echo $modalidad["noIntegrantes"] ?>
													</a>
												<?php elseif($session -> offsetExists("equipoCodigo")): ?>
													<a class="list-group-item">
														<strong>Nombre:</strong> <?php echo $equipoCodigo["nombre"]; ?>
													</a>
													<a class="list-group-item">
														<strong>Integrantes: </strong> <?php echo $equipoCodigo["noIntegrantes"] ?>
													</a>
												<?php endif; ?>
											</div>
										</div>
									</div>
								</div>
								<a class="list-group-item"><strong>Estado:</strong> <?php echo $estado["nombre"]; ?></a>
								<a class="list-group-item"><strong>Día:</strong> <?php echo date_format(date_create($diaHit["dia"]["fechaRealizacion"]), "d-m-y"); ?></a>
								<a class="list-group-item"><strong>Bloque:</strong> <?php echo $diaHit["hit"]["horario"]; ?></a>
								<a class="list-group-item">
									<strong>Método de Pago:</strong>
									<?php if ($session -> offsetExists("metodoPago")): ?>
										<?php if ($metodoPago["rdbMetodoPago"] === "tarjeta"): ?>
											Tarjeta de crédito o débito <img src="<?php echo $this -> basePath(); ?>/css/Imagenes/tarjetas.jpg" height="30" />
										<?php else: ?>
											Efectivo - Sucursal
											<?php if ($metodoPago["rdbSucursal"] === "OXXO"): ?>
												Oxxo <img src="<?php echo $this -> basePath(); ?>/css/Imagenes/tienda_oxxo.png" height="30" />
											<?php elseif ($metodoPago["rdbSucursal"] === "SEVEN_ELEVEN"): ?>
												Seven Eleven <img src="<?php echo $this -> basePath(); ?>/css/Imagenes/tienda_seven.png" height="30" />
											<?php elseif ($metodoPago["rdbSucursal"] === "EXTRA"): ?>
												Extra <img src="<?php echo $this -> basePath(); ?>/css/Imagenes/tienda_extra.png" height="30" />
											<?php elseif ($metodoPago["rdbSucursal"] === "CHEDRAUI"): ?>
												Chedraui <img src="<?php echo $this -> basePath(); ?>/css/Imagenes/tienda_chedraui.png" height="30" />
											<?php elseif ($metodoPago["rdbSucursal"] === "FARMACIA_BENAVIDES"): ?>
												Farmacias Benavides <img src="<?php echo $this -> basePath(); ?>/css/Imagenes/tienda_benavides.png" height="30" />
											<?php elseif ($metodoPago["rdbSucursal"] === "FARMACIA_ESQUIVAR"): ?>
												Farmacias Esquivar <img src="<?php echo $this -> basePath(); ?>/css/Imagenes/tienda_esquivar.png" height="30" />
											<?php endif; ?>
										<?php endif; ?>
									<?php else: ?>
										n/a
									<?php endif; ?>
								</a>
								<a class="list-group-item">
									<strong>Precio:</strong> 
									<?php echo ($session -> offsetExists("equipoCodigo")) ? "n/a" : "\$$precio"; ?>
								</a>
							</div>
							<form action="<?php echo $this -> basePath(); ?>/application/cuenta/confirmardatos" method="post">
								<?php if($session -> offsetExists("equipoCodigo")): ?>
									<input type="submit" value="Inscribirse" class="btn btn-primary btn-lg" />
								<?php else: ?>
									<input type="submit" value="Realizar Pago" class="btn btn-primary btn-lg" />
								<?php endif; ?>
							</form>
						<?php endif; ?>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-5 col-xs-5">
			<?php if ($session -> offsetExists("equipoCodigo")): ?>
				<a href="<?php echo $this -> basePath(); ?>/application/cuenta/elegirmodalidad" class="btn btn-warning btn-lg btn-block" style="white-space: normal">Regresar a elegir modalidad</a>
			<?php else: ?>
				<a href="<?php echo $this -> basePath(); ?>/application/cuenta/metodopago" class="btn btn-warning btn-lg btn-block" style="white-space: normal">Regresar a método de pago</a>
			<?php endif; ?>
			<br>
			<a href="<?php echo $this -> basePath(); ?>/application/cuenta/index" class="btn btn-danger btn-lg btn-block">Cancelar</a>	
		</div>
	</div>
</div>