<script>
	(function() {
		$("#navbarCollapse ul li").each(function() {
			$(this).removeClass("active");
		});
		$("#navbarCollapse ul").children().last().addClass("active");
		$("#navbarCollapse ul li a").children().last().html("Inscripciones");
		$("#navbarCollapse ul li").children().last().attr("href", "<?php echo $this -> basePath(); ?>/application/cuenta/index");
		document.title = "Finalizar Inscripción - InflaRun";
	})();
</script>
<div id="cuentaBody" class="container-fluid">
	<div class="row">
		<div class="col-md-7 col-xs-7">
			<div class="panel panel-success">
				<div class="panel-heading">
					<strong>Finalizando inscripción...</strong>
				</div>
				<div class="panel-body">
					<div class="col-md-12">
						<?php
							#$resultado =
							#	(new \Application\Model\Controller\Cuenta\Pagos\PagoEfectivo) -> consultarOrden("PFCPE4782S4860I9708");
						?>
						<pre>
							<?php print_r(\Application\Model\Controller\Cuenta\Handler\AdminHandler::aceptarOrdenesPagadas()); ?>
						</pre>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-5 col-xs-5">
			<br>
			<a href="<?php echo $this -> basePath(); ?>/application/cuenta/index" class="btn btn-danger btn-lg btn-block">Finalizar</a>	
		</div>
	</div>
</div>