<?php
	$session = (new \Zend\Session\Container("usuario"));
	$inscripcionDetalles = $session -> offsetGet("inscripcionDetalles");
	
	if ($session -> offsetExists("modalidad"))
		$session -> offsetUnset("modalidad");
	
	if ($session -> offsetExists("equipoCodigo"))
		$session -> offsetUnset("equipoCodigo");
	
	if ($session -> offsetExists("diaHit"))
		$session -> offsetUnset("diaHit");
	
	if ($session -> offsetExists("metodoPago"))
		$session -> offsetUnset("metodoPago");
	
	if ($session -> offsetExists("datosBancarios"))
		$session -> offsetUnset("datosBancarios");
?>
<script>
	(function() {
		$("#navbarCollapse ul li").each(function() {
			$(this).removeClass("active");
		});
		$("#navbarCollapse ul").children().last().addClass("active");
		$("#navbarCollapse ul li a").children().last().html("Inscripciones");
		$("#navbarCollapse ul li").children().last().attr("href", "<?php echo $this -> basePath(); ?>/application/cuenta/index");
		document.title = "Modalidad - InflaRun";
	})();
	
	$(document).ready(function() {
		$("#rdbIndividual").click(function() {
			$("#equipoAccordion,#codigoAccordion").removeClass("in");
			$("#equipoAccordion,#codigoAccordion").addClass("collapse");
		});
		$("#rdbEquipo").click(function() {
			$("#equipoAccordion").removeClass("collapse");
			$("#equipoAccordion").addClass("in");
			$("#codigoAccordion").removeClass("in");
			$("#codigoAccordion").addClass("collapse");
			$("#nombreEquipo").focus();
		});
		$("#rdbCodigo").click(function() {
			$("#codigoAccordion").removeClass("collapse");
			$("#codigoAccordion").addClass("in");
			$("#equipoAccordion").removeClass("in");
			$("#equipoAccordion").addClass("collapse");
			$("#codigoInscripcion").focus();
		});
	});
</script>
<div id="cuentaBody" class="container-fluid">
	<div class="row">
		<div class="col-md-7 col-xs-7">
			<div class="panel panel-success">
				<div class="panel-heading">
					<strong>Elige la modalidad de tu inscripción</strong>
				</div>
				<div class="panel-body">
					<?php if (isset($this -> Error)): ?>
						<div class="alert alert-danger fade in">
							<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
							<?php echo $this -> Error; ?>
						</div>
					<?php endif; ?>
					<div class="col-md-12">
						<form action="<?php echo $this -> basePath(); ?>/application/cuenta/elegirmodalidad" method="post">
							<label class="radio">
								<input id="rdbIndividual" type="radio" name="rdbModalidad" value="individual" checked />
								Individual
							</label>
							<label class="radio">
								<input id="rdbEquipo" type="radio" name="rdbModalidad" value="equipo" />
								Quiero inscribir a mi equipo
							</label>
							<div class="panel-group">
								<div class="panel panel-success">
									<div id="equipoAccordion" class="panel-collapse collapse">
										<div class="panel-body">
											<div class="form-group">
												<label>Nombre de tu equipo:</label>
												<input type="text" id="nombreEquipo" name="nombreEquipo" class="form-control" />
											</div>
											<div class="form-group">
												<label>Número de integrantes:</label>
												<input type="text" id="noIntegrantes" name="noIntegrantes" class="form-control" />
											</div>
										</div>
									</div>
								</div>
							</div>
							<label class="radio">
								<input id="rdbCodigo" type="radio" name="rdbModalidad" value="codigo" />
								Alguien ya pagó mi inscripción
							</label>
							<div class="panel-group">
								<div class="panel panel-success">
									<div id="codigoAccordion" class="panel-collapse collapse">
										<div class="panel-body">
											<div class="form-group">
												<label>Ingresa tu código de inscripción:</label>
												<input type="text" id="codigoInscripcion" name="codigoInscripcion" class="form-control" />
											</div>
										</div>
									</div>
								</div>
							</div>
							<input type="submit" value="Continuar" class="btn btn-primary btn-lg" />
						</form>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-5 col-xs-5">
			<a href="<?php echo $this -> basePath(); ?>/application/cuenta/paginaevento?id=<?php echo $inscripcionDetalles["detallesEvento"] -> getIdDetallesEvento(); ?>" class="btn btn-warning btn-lg btn-block" style="white-space: normal">Regresar a la página del evento</a>
			<br>
			<a href="<?php echo $this -> basePath(); ?>/application/cuenta/index" class="btn btn-danger btn-lg btn-block">Cancelar</a>	
		</div>
	</div>
</div>