<?php
	$session = new \Zend\Session\Container("usuario");
	$usuario = $session -> offsetGet("usuario");
	$anyoActual = (int)explode("-", date("y-m-d"))[0];
	
	if ($session -> offsetExists("datosBancarios"))
		$session -> offsetUnset("datosBancarios");
	
	try {
		$dao = new Application\Model\Dao\EstadoDao();
		$estado = $dao -> consultaGenerica("SELECT * FROM Estado WHERE idEstado = ?", array($usuario -> getIdEstado()))[0];
	} catch (\Exception $ex) {
		header("Location: {$this -> basePath()}/application/cuenta/index");
		die();
	}
?>
<script>
	(function() {
		$("#navbarCollapse ul li").each(function() {
			$(this).removeClass("active");
		});
		$("#navbarCollapse ul").children().last().addClass("active");
		$("#navbarCollapse ul li a").children().last().html("Inscripciones");
		$("#navbarCollapse ul li").children().last().attr("href", "<?php echo $this -> basePath(); ?>/application/cuenta/index");
		document.title = "Datos Bancarios - InflaRun";
	})();
</script>
<div id="cuentaBody" class="container-fluid">
	<div class="row">
		<div class="col-md-7 col-xs-7">
			<div class="panel panel-success">
				<div class="panel-heading">
					<strong>Ingresa tus datos bancarios</strong>
				</div>
				<div class="panel-body">
					<div class="col-md-12">
						<?php if(isset($this -> Error)): ?>
							<div class="alert alert-danger fade in">
								<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
								<?php echo $this -> Error["message"]; ?>
							</div>
						<?php endif; ?>
						<form action="<?php echo $this -> basePath(); ?>/application/cuenta/formulariotarjeta" method="post">
							<div class="form-group">
								<label>Nombre:</label>
								<input type="text" name="nombre" class="form-control" value="<?php echo $usuario -> getNombre(); ?>" />
							</div>
							<div class="form-group">
								<label>Apellidos:</label>
								<input type="text" name="apellidos" class="form-control" value="<?php echo "{$usuario -> getAPaterno()} {$usuario -> getAMaterno()}"; ?>" />
							</div>
							<div class="form-group">
								<label>E-mail:</label>
								<input type="text" name="email" class="form-control" value="<?php echo $usuario -> getCorreo(); ?>" />
							</div>
							<div class="form-group">
								<label>Teléfono (10 dígitos):</label>
								<input type="text" name="telefono" class="form-control" />
							</div>
							<div class="form-group">
								<label>Celular (10 dígitos):</label>
								<input type="text" name="celular" class="form-control" />
							</div>
							<div class="form-group">
								<label>Número de tarjeta:</label>
								<input type="text" name="numeroTarjeta" class="form-control" />
							</div>
							<div class="form-group">
								<label>Fecha de expiración (MM/YY):</label>
								<div class="row">
									<div class="col-md-6 col-xs-6">
										<select name="mesExpiracion" class="form-control">
										<option value="01">01</option>
										<option value="02">02</option>
										<option value="03">03</option>
										<option value="04">04</option>
										<option value="05">05</option>
										<option value="06">06</option>
										<option value="07">07</option>
										<option value="08">08</option>
										<option value="09">09</option>
										<option value="10">10</option>
										<option value="11">11</option>
										<option value="12">12</option>
									</select>
									</div>
									<div class="col-md-6 col-xs-6">
										<select name="anyoExpiracion" class="form-control">
											<?php for ($i = $anyoActual; $i < $anyoActual + 15; $i++): ?>
												<option value="<?php echo $i; ?>"><?php echo $i; ?></option>
											<?php endfor; ?>
										</select>
									</div>
								</div>
							</div>
							<div class="form-group">
								<label>Código Cvv2:</label>
								<a href="#" data-toggle="modal" data-target="#codigoCvt">Dónde encontrarlo</a>
								<div id="codigoCvt" class="modal fade">
									<div class="modal-dialog">
										<div class="modal-content">
											<div class="modal-header">
												<button class="close" data-dismiss="modal">&times;</button>
											</div>
											<div class="modal-body">
												<img src="<?php echo $this -> basePath(); ?>/css/Imagenes/cvttarjeta.jpg" class="img-responsive" />
											</div>
										</div>
									</div>
								</div>
								<input type="text" name="cvt" class="form-control" />
							</div>
							<div class="form-group">
								<label>Calle y número:</label>
								<input type="text" name="calleyNumero" class="form-control" />
							</div>
							<div class="form-group">
								<label>Colonia:</label>
								<input type="text" name="colonia" class="form-control" />
							</div>
							<div class="form-group">
								<label>Delegación o municipio:</label>
								<input type="text" name="municipio" class="form-control" />
							</div>
							<div class="form-group">
								<label>Estado:</label>
								<input type="text" name="estado" class="form-control" value="<?php echo $estado["nombre"]; ?>" />
							</div>
							<div class="form-group">
								<label>País:</label>
								<input type="text" name="pais" class="form-control" />
							</div>
							<div class="form-group">
								<label>Código postal:</label>
								<input type="text" name="cp" class="form-control" />
							</div>
							<input type="submit" value="Continuar" class="btn btn-primary btn-lg" />
						</form>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-5 col-xs-5">
			<a href="<?php echo $this -> basePath(); ?>/application/cuenta/metodopago" class="btn btn-warning btn-lg btn-block" style="white-space: normal">Regresar a método de pago</a>
			<br>
			<a href="<?php echo $this -> basePath(); ?>/application/cuenta/index" class="btn btn-danger btn-lg btn-block">Cancelar</a>	
		</div>
	</div>
</div>