<?php
	$session = new \Zend\Session\Container("user");
	$evento = $session -> offsetGet("user")["evento"];
	$usuario = $session -> offsetGet("user")["usuario"];
	$anyoActual = (int)explode("-", date("y-m-d"))[0];
?>
<script>
	(function() {
		$("#navbarCollapse ul li").each(function() {
			$(this).removeClass("active");
		});
		$("#navbarCollapse ul").children().last().addClass("active");
		document.title = "Inscripción a <?php echo $evento["nombre"]; ?> - InflaRun";
	})();
		
	function cancelarInscripcion() {
		$("#btnCancelar").click(function() {
			BootstrapDialog.show({
				title: "Cancelar Inscripción",
				message: "¿Realmente quiere cancelar su inscripción?",
				type: BootstrapDialog.TYPE_WARNING,
				buttons: [{
					label: "Cancelar mi inscripción",
					icon: "glyphicon glyphicon-remove-circle",
					cssClass: "btn-warning",
					action: function() {
						window.location = "<?php echo $this -> basePath(); ?>/application/cuenta/cancelarinscripcion";
					}
				}, {
					label: "Continuar con mi inscripción",
					icon: "glyphicon glyphicon-ok-circle",
					cssClass: "btn-success",
					action: function(dialog) {
						dialog.close();
					}
				}]
			});
		});
	}
	
	function continuarInscripcion() {
		var progressBar = "<div class='progress'>"
			+	"<div class='progress-bar progress-bar-striped active' style='width:100%'>"
			+		"Estamos validando tus datos. ¡Solo un momento!"
			+	"</div>"
			+ "</div>";
	
		$("#btnContinuar").click(function() {
			function habilitarDialogError(dialog, message) {
				dialog.setTitle("Error en los Campos de Entrada");
				dialog.setMessage("<strong>Recuerda:</strong> " + message);
				dialog.setType(BootstrapDialog.TYPE_DANGER);
				dialog.setClosable(true);
				dialog.setButtons([{
					label: "Cerrar",
					icon: "glyphicon glyphicon-remove",
					cssClass: "btn-danger",
					action: function(dialog) {
						dialog.close();
					}
				}]);
			}
			
			function habilitarDialogCorrecto(dialog, message) {
				dialog.setTitle("Datos Correctos");
				dialog.setMessage(message);
				dialog.setType(BootstrapDialog.TYPE_INFO);
			}
			
			var dialog = BootstrapDialog.show({
				title: "Validando...",
				message: progressBar,
				type: BootstrapDialog.TYPE_PRIMARY,
				closable: false
			});
			
			$.post("<?php echo $this -> basePath(); ?>/application/cuenta/inscripcionesvalidartarjeta", {
				nombre: $("#nombre").val(),
				apellidos: $("#apellidos").val(),
				correo: $("#correo").val(),
				telefono: $("#telefono").val(),
				celular: $("#celular").val(),
				numeroTarjeta: $("#numeroTarjeta").val(),
				mesExpiracion: $("#mesExpiracion").val(),
				anyoExpiracion: $("#anyoExpiracion").val(),
				cvt: $("#cvt").val(),
				calleyNumero: $("#calleyNumero").val(),
				colonia: $("#colonia").val(),
				municipio: $("#municipio").val(),
				estado: $("#estado").val(),
				pais: $("#pais").val(),
				cp: $("#cp").val()
			}, function(response) {
				if (response.estatus !== 0) {
					habilitarDialogError(dialog, response.message);
				} else {
					habilitarDialogCorrecto(dialog, response.message);
					setTimeout(function() {
						window.location = "<?php echo $this -> basePath(); ?>/application/cuenta/inscripcionesconfirmardatos";
					}, 2000);
				}
			});
		});
	}
	
	$(document).ready(function() {
		cancelarInscripcion();
		continuarInscripcion();
	});
</script>
<div id="cuentaBody" class="container-fluid">
	<div class="row">
		<div class="col-sm-12 col-xs-12">
			<h1>Inscripción a la carrera: <?php echo $evento["nombre"]; ?></h1>
			<br>
			<div class="panel panel-info">
				<div class="panel-heading">
					<strong>Ingresa tus datos bancarios</strong>
				</div>
				<div class="panel-body">
					<div class="col-sm-6">
						<div class="form-group">
							<label>Nombre:</label>
							<input type="text" id="nombre" class="form-control" value="<?php echo $usuario["nombre"]; ?>" />
						</div>
						<div class="form-group">
							<label>Apellidos:</label>
							<input type="text" id="apellidos" class="form-control" value="<?php echo "{$usuario["paterno"]} {$usuario["materno"]}"; ?>" />
						</div>
						<div class="form-group">
							<label>Correo electrónico:</label>
							<input type="text" id="correo" class="form-control" value="<?php echo $usuario["correo"]; ?>" />
						</div>
						<div class="form-group">
							<label>Teléfono (10 dígitos):</label>
							<input type="text" id="telefono" class="form-control" />
						</div>
						<div class="form-group">
							<label>Celular (10 dígitos)</label>
							<input type="text" id="celular" class="form-control" />
						</div>
						<div class="form-group">
							<label>Número de tarjeta:</label>
							<input type="text" id="numeroTarjeta" class="form-control" />
						</div>
						<div class="form-group">
							<label>Fecha de expiración (MM/YY):</label>
							<div class="row">
								<div class="col-sm-6 col-xs-6">
									<select id="mesExpiracion" class="form-control">
										<option value="01">01</option>
										<option value="02">02</option>
										<option value="03">03</option>
										<option value="04">04</option>
										<option value="05">05</option>
										<option value="06">06</option>
										<option value="07">07</option>
										<option value="08">08</option>
										<option value="09">09</option>
										<option value="10">10</option>
										<option value="11">11</option>
										<option value="12">12</option>
									</select>
								</div>
								<div class="col-sm-6 col-xs-6">
									<select id="anyoExpiracion" class="form-control">
										<?php for ($i = $anyoActual; $i < $anyoActual + 15; $i++): ?>
											<option value="<?php echo $i; ?>"><?php echo $i; ?></option>
										<?php endfor; ?>
									</select>
								</div>
							</div>
						</div>
					</div>
					<div class="col-sm-6">
						<div class="form-group">
							<label>Código CVV2:</label>
							<a href="#" data-toggle="modal" data-target="#codigoCvt">Dónde encontrarlo</a>
							<div id="codigoCvt" class="modal fade">
								<div class="modal-dialog">
									<div class="modal-content">
										<div class="modal-header">
											<button class="close" data-dismiss="modal">&times;</button>
										</div>
										<div class="modal-body">
											<img src="<?php echo $this -> basePath(); ?>/css/Imagenes/cvttarjeta.jpg" class="img-responsive" />
										</div>
									</div>
								</div>
							</div>
							<input type="text" id="cvt" class="form-control" />
						</div>
						<div class="form-group">
							<label>Calle y número:</label>
							<input type="text" id="calleyNumero" class="form-control" />
						</div>
						<div class="form-group">
							<label>Colonia:</label>
							<input type="text" id="colonia" class="form-control" />
						</div>
						<div class="form-group">
							<label>Delegación o municipio:</label>
							<input type="text" id="municipio" class="form-control" />
						</div>
						<div class="form-group">
							<label>Estado:</label>
							<input type="text" id="estado" class="form-control" />
						</div>
						<div class="form-group">
							<label>País:</label>
							<input type="text" id="pais" class="form-control" />
						</div>
						<div class="form-group">
							<label>Código postal:</label>
							<input type="text" id="cp" class="form-control" />
						</div>
					</div>
				</div>
			</div>
			<br>
			<div class="row">
				<div class="col-sm-6 col-xs-6">
					<button id="btnCancelar" class="btn btn-danger btn-lg btn-block" style="white-space: normal;">Cancelar Inscripción</button>
				</div>
				<div class="col-sm-6 col-xs-6">
					<button id="btnContinuar" class="btn btn-primary btn-lg btn-block">Continuar</button>
				</div>
			</div>
			<br>
		</div>	
	</div>
</div>