<?php
	$fechaHandler = new \Application\Model\Controller\Cuenta\Handler\FechasHandler();
	$session = new \Zend\Session\Container("user");
	$evento = $session -> offsetGet("user")["evento"];
	$usuario = $session -> offsetGet("user")["usuario"];
	$equipo = $session -> offsetGet("user")["equipo"];
	$diaHit = $session -> offsetGet("user")["diaHit"];
	$playera = $session -> offsetGet("user")["playera"];
	$metodoPago = $session -> offsetGet("user")["metodoPago"];
?>
<script>
	(function() {
		$("#navbarCollapse ul li").each(function() {
			$(this).removeClass("active");
		});
		$("#navbarCollapse ul").children().last().addClass("active");
		document.title = "Inscripción a <?php echo $evento["nombre"]; ?> - InflaRun";
	})();
	
	function habilitarDialogExito(dialog, message) {
		dialog.setTitle("¡Te has inscrito con éxito a InflaRun!");
		dialog.setMessage(message);
		dialog.setType(BootstrapDialog.TYPE_SUCCESS);
		dialog.setButtons([{
			label: "Finalizar",
			icon: "glyphicon glyphicon-ok",
			cssClass: "btn-success",
			action: function() {
				window.location = "<?php echo $this -> basePath(); ?>/application";
			}
		}]);
	}
	
	function habilitarDialogError(dialog, message) {
		dialog.setTitle("Error en inscripción");
		dialog.setMessage("<strong>Lo sentimos, ocurrió un error al procesar tu inscripción:</strong> " + message);
		dialog.setType(BootstrapDialog.TYPE_DANGER);
		dialog.setClosable(true);
		dialog.setButtons([{
			label: "Regresar a Inscripciones",
			icon: "glyphicon glyphicon-remove",
			cssClass: "btn-danger",
			action: function() {
				window.location = "<?php echo $this -> basePath(); ?>/application/cuenta/cancelarinscripcion";
			}
		}]);
	}
	
	function cancelarInscripcion() {
		$("#btnCancelar").click(function() {
			BootstrapDialog.show({
				title: "Cancelar Inscripción",
				message: "¿Realmente quiere cancelar su inscripción?",
				type: BootstrapDialog.TYPE_WARNING,
				buttons: [{
					label: "Cancelar mi inscripción",
					icon: "glyphicon glyphicon-remove-circle",
					cssClass: "btn-warning",
					action: function() {
						window.location = "<?php echo $this -> basePath(); ?>/application/cuenta/cancelarinscripcion";
					}
				}, {
					label: "Continuar con mi inscripción",
					icon: "glyphicon glyphicon-ok-circle",
					cssClass: "btn-success",
					action: function(dialog) {
						dialog.close();
					}
				}]
			});
		});
	}
	
	function finalizarInscripcion() {
		var progressBar = "<div class='progress'>"
			+	"<div class='progress-bar progress-bar-striped active' style='width:100%'>"
			+		"Estamos generando tu inscripción. ¡Solo un momento!"
			+	"</div>"
			+ "</div>";

		$("#btnContinuar").click(function() {
			var dialog = BootstrapDialog.show({
				title: "Inscripción en progreso...",
				message: progressBar,
				type: BootstrapDialog.TYPE_PRIMARY,
				closable: false
			});
			
			$.get("<?php echo $this -> basePath(); ?>/application/cuenta/inscripcionesfinalizar", function(response) {
				if (response.estatus === 0) {
					habilitarDialogExito(dialog, response.message);
				} else {
					habilitarDialogError(dialog, response.message);
				}
			});
		});
	}
	
	$(document).ready(function() {
		cancelarInscripcion();
		finalizarInscripcion();
	});
</script>
<div id="cuentaBody" class="container-fluid">
	<div class="row">
		<div class="col-sm-12 col-xs-12">
			<h1>Inscripción a la carrera: <?php echo $evento["nombre"]; ?></h1>
			<br>
			<div class="panel panel-primary">
				<div class="panel-heading">
					<strong>Confirma los datos de tu inscripción</strong>
				</div>
				<div class="panel-body">
					<div class="list-group">
						<a class='list-group-item list-group-item-info'><strong>Evento</strong></a>
						<a class="list-group-item"><strong>Evento:</strong> <?php echo $evento["nombre"]; ?></a>
						<a class="list-group-item"><strong>Dirección:</strong> <?php echo $evento["direccion"]; ?></a>
						<a class='list-group-item'><strong>Precio: $</strong><?php echo $evento["precio"]; ?></a>
						<a class="list-group-item"><strong>Contacto:</strong> <?php echo $evento["correoContacto"]; ?></a>
						<a class="list-group-item list-group-item-success"><strong>Información Personal</strong></a>
						<a class="list-group-item">
							<strong>Corredor:</strong>
							<?php echo "{$usuario["nombre"]} {$usuario["paterno"]} {$usuario["materno"]}"; ?>
						</a>
						<a class="list-group-item">
							<strong>Sexo:</strong> <?php echo ($usuario["sexo"] === "H") ? "Hombre" : "Mujer"; ?>
						</a>
						<a class='list-group-item'>
							<strong>Fecha de Nacimiento:</strong>
							<?php echo $fechaHandler -> traducirFecha($usuario["fechaNacimiento"]); ?>
						</a>
						<a class='list-group-item'><strong>Correo electrónico:</strong> <?php echo $usuario["correo"]; ?></a>
						<a class='list-group-item'><strong>Playera:</strong> <?php echo "{$playera["tamanyo"]["talla"]}"; ?></a>
						<a class='list-group-item list-group-item-warning'><strong>Inscripción</strong></a>
						<a class="list-group-item">
							<strong>Modalidad:</strong>
							<?php echo ($equipo["modalidad"] === "individual") ? "Individual" : "En Equipo"; ?>
						</a>
						<?php if ($equipo["modalidad"] === "equipo"): ?>
							<a class="list-group-item">
								<strong>Nombre:</strong>
								<?php echo $equipo["nombre"]; ?>
							</a>
							<a class="list-group-item">
								<strong>Número de integrantes:</strong>
								<?php echo $equipo["noIntegrantes"]; ?>
							</a>
						<?php endif; ?>
						<a class='list-group-item'><strong>Día:</strong> <?php echo $fechaHandler -> traducirFecha($diaHit["dia"]["fecha"]); ?></a>
						<a class='list-group-item'><strong>Bloque:</strong> <?php echo $diaHit["hit"]["horario"] ?></a>
						<a class='list-group-item list-group-item-danger'><strong>Pago</strong></a>
						<a class='list-group-item'>
							<strong>Método de Pago:</strong>
							<?php if($metodoPago["metodo"] === "tarjeta"): ?>
								Tarjeta de crédito o débito <img src="<?php echo $this -> basePath(); ?>/css/Imagenes/tarjetas.jpg" height="30" />
							<?php else: ?>
								Efectivo - Sucursal
								<?php if ($metodoPago["sucursal"] === "OXXO"): ?>
									Oxxo <img src="<?php echo $this -> basePath(); ?>/css/Imagenes/tienda_oxxo.png" height="30" />
								<?php elseif ($metodoPago["sucursal"] === "SEVEN_ELEVEN"): ?>
									Seven Eleven <img src="<?php echo $this -> basePath(); ?>/css/Imagenes/tienda_seven.png" height="30" />
								<?php elseif ($metodoPago["sucursal"] === "EXTRA"): ?>
									Extra <img src="<?php echo $this -> basePath(); ?>/css/Imagenes/tienda_extra.png" height="30" />
								<?php elseif ($metodoPago["sucursal"] === "ELEKTRA"): ?>
									Elektra <img src="<?php echo $this -> basePath(); ?>/css/Imagenes/tienda_elektra.png" height="30" />
								<?php elseif ($metodoPago["sucursal"] === "COPPEL"): ?>
									Coppel <img src="<?php echo $this -> basePath(); ?>/css/Imagenes/tienda_coppel.png" height="30" />
								<?php elseif ($metodoPago["sucursal"] === "CHEDRAUI"): ?>
									Chedraui <img src="<?php echo $this -> basePath(); ?>/css/Imagenes/tienda_chedraui.png" height="30" />
								<?php elseif ($metodoPago["sucursal"] === "FARMACIA_BENAVIDES"): ?>
									Farmacias Benavides <img src="<?php echo $this -> basePath(); ?>/css/Imagenes/tienda_benavides.png" height="30" />
								<?php elseif ($metodoPago["sucursal"] === "FARMACIA_ESQUIVAR"): ?>
									Farmacias Esquivar <img src="<?php echo $this -> basePath(); ?>/css/Imagenes/tienda_esquivar.png" height="30" />
								<?php endif; ?>
							<?php endif; ?>
						</a>
						<a class='list-group-item'><strong>Precio Total: $</strong><?php echo $metodoPago["precio"]; ?></a>
					</div>
				</div>
			</div>
			<div id="terminosCondiciones" class="modal fade" role="dialog">
				<div class="modal-dialog">
					<div class="modal-contentAviso">
						<div class="modal-header">
							<button class="close" data-dismiss="modal">&times;</button>
							<h1 class="modal-title">Términos y Condiciones</h1>
						</div>
						<div class="modal-body">
							<div class="sub">Términos y Condiciones</div>
							<p>
								Estos son los términos y condiciones de participación en la carrera INFLARUN, aplica cualquier
								sede donde se realice; declaración de exoneración de responsibilidades y autorización.
							</p>
							<p>
								<strong>1.-</strong> Esta página web y todo su contenido son propiedad de INFLARUN S.A. de C.V.
								con todos los derechos reservados. El uso de cualquier información, salvo lo dispuesto en los
								presentes Términos y Condiciones, sin el permiso escrito del propietario de la información está
								estrictamente prohibido. Usted puede descargar, visualizar o imprimir la información de esta
								página web únicamente para uso personal no comercial.
							</p>
							<p>
								<strong>2.-</strong> El registro e inscripción de los usuarios es única y exclusivamente dentro
								del portal web y en las fechas señaladas en la convocatoria presente. <strong>No habrá venta
								de boletos el día del evento</strong> bajo ninguna circunstancia.
							</p>
							<p>
								<strong>3.-</strong> INFLARUN se compromete a proteger y cifrar todas las transacciones y pagos
								realizados con tarjeta de crédito/débito, así como toda la información personal dentro del sitio
								mediante un certificado de seguridad SSL.
							</p>
							<p>
								<strong>4.-</strong> Al suscribirme al boletín se acepta recibir correos relacionados con el
								evento actual, próximos eventos e información relacionada con la carrera INFLARUN.
							</p>
							<p>
								<strong>5.-</strong> Al inscribirme, realizar el pago de la inscripción, reclamar el kit de
								competencia y participar en la carrera, entiendo y acepto ls términos y condiciones de
								participación en la carrera INFLARUN en cualquiera de sus sedes, aquí descritos.
							</p>
							<p>
								<strong>6.-</strong> Acepto las condiciones de inscripción y participación.
							</p>
							<p>
								<strong>6.1.-</strong> Entiendo que es obligatorio proporcionar todos mis datos de contacto,
								sin importar la categoría u horario de bloque en el que me he inscrito.
							</p>
							<p>
								<strong>7.-</strong> Declaro que participo en la carrera de forma libre y por voluntad propia.
							</p>
							<p>
								<strong>8.-</strong> Entiendo que la inscripción en la carrera me da el derecho de participar
								en la competencia.
							</p>
							<p>
								<strong>9.-</strong> Es de mi conocimiento que en caso de no poder asistir a la carrera, bajo
								ninguna circunstancia podré exigir un reembolso del valor de la inscripción.
							</p>
							<p>
								<strong>10.-</strong> Acepto de que en caso de cancelación del evento por causas de fuerza mayor
								o fortuitos, ajenos a la organización, no habrá devoluciones del valor de la inscripción.
							</p>
							<p>
								<strong>11.-</strong> Soy conciente de que en caso de no poder asistir a recoger el kit de
								competencia en las fechas establecidas por la organización, no podré reclamarlo posteriormente.
							</p>
							<p>
								<strong>12.-</strong> Comprendo que la entrega de playeras será sujeta a existencias y que la
								organización no se hace responsable por falta de ellas.
							</p>
							<p>
								<strong>13.-</strong> Al participar en esta carrera, declaro mi comprensión y aceptación acerca
								de la naturaleza de las actividades relacionadas, por lo que hago constar que cuento con buen
								estado de salud para participar en dicha carrera, entiendo y acepto que mi participación en la
								carrera INFLARUN, dada su naturaleza puede representar riesgos de accidentes que ocasionen
								lesiones graves antes, durante y después, incluyendo discapacidad parcial o total, temporal o
								permanente y hasta la perdida de la vida, por lo que acepto la responsabilidad total por cualquier
								incidente que pueda ser motivo de mi participación en la carrera, y renuncio a cualquier acción
								legal que pudiera ejercerse en contra de todo el personal organizador, trabajadores de INFLARUN
								en <strong>cualquier sede</strong> donde se realice la carrera.
							</p>
							<p>
								<strong>14.-</strong> Declaro que conozco el lugar, la información general y particular de la carrera.
							</p>
							<p>
								<strong>15.-</strong> Entiendo que la carrera está sujeta a cambios sin previo aviso.
							</p>
							<p>
								<strong>16.-</strong> Declaro que conozco y he leído atentamente el reglamento de la carrera.
							</p>
							<p>
								<strong>17.-</strong> Habiendo leído esta declaración, conociendo estos hechos y considerando que
								los acepto por el hecho de participar en la carrera INFLARUN yo, en mi nombre y en el de cualquier
								persona que actúe en mi represntación, sucesores, legatarios u herederos, libero y eximo de cualquier
								responsabilidad, reclamo, indemnización, costo por daño, perjuicio reclamado o lucro cesante a los
								organizadores de INFLARUN, aliados, patrocinadores, sus representantes y sucesores de todo reclamo o
								responsabilidad de cualquier tipo, que surja de mi participación en esta competencia, incluso en
								circunstancias de caso fortuito o fuerza mayor, en razón a que la actividad durante el desarrollo
								de la carrera se encontrará bajo mi control y ejecución exclusiva como participante, así como cualquier
								extravío, robo y/o hurto que pudiera sufrir.
							</p>
							<p>
								<strong>18.-</strong> Autorizo a los organizadores y operadores de la carrera INFLARUN, aliados y
								patrocinadores el uso de fotografías, película, video, grabación y cualquier otro medio de registro
								de este evento para cualquier uso legítimo sin compensación económica alguna.
							</p>
							<p>
								<strong>19.-</strong> Estos términos y condiciones están sujetos a cambios sin previo aviso, con la
								actualización de esta publicación.
							</p>
							<p>
								<strong>Acepto los términos y condiciones establecidos en el presente documento, los cuales he
								entendido y aceptado voluntariamente.</strong>
							</p>
						</div>
					</div>
				</div>
			</div>
			<p>
				Al hacer clic en el botón <strong>Finalizar Inscripción</strong> estás aceptando los 
				<a href="#" data-toggle="modal" data-target="#terminosCondiciones">Términos y Condiciones</a> y el
				<a href="#" data-toggle="modal" data-target="#aviso">Aviso de Privacidad</a>.
			</p>
			<br>
			<div class="row">
				<div class="col-sm-6 col-xs-6">
					<button id="btnCancelar" class="btn btn-danger btn-lg btn-block" style="white-space: normal;">Cancelar Inscripción</button>
				</div>
				<div class="col-sm-6 col-xs-6">
					<button id="btnContinuar" class="btn btn-primary btn-lg btn-block" style="white-space: normal;">Finalizar Inscripción</button>
				</div>
			</div>
			<br>
		</div>	
	</div>
</div>