<?php
	$session = (new \Zend\Session\Container("usuario"));
	$message = $session -> offsetGet("message");
	$usuario = $session -> offsetGet("usuario");
	
	try {
		$dao = new \Application\Model\Dao\DetallesEventoDao();
		$detallesEvento = $dao -> buscar((new \Application\Model\Pojo\DetallesEvento()) -> setIdDetallesEvento($this -> idDetallesEvento));
		$nombreEvento = $dao -> consultaGenerica("SELECT * FROM Evento WHERE idEvento = ?", array($detallesEvento -> getIdEvento()))[0];
		$estado = $dao -> consultaGenerica("SELECT * FROM Estado WHERE idEstado = ?", array($detallesEvento -> getIdEstado()))[0];
		$diasEvento = $dao -> consultaGenerica("SELECT * FROM DiaEvento WHERE idDetallesEvento = ?", array($detallesEvento -> getIdDetallesEvento()));
		/*$usuarioEquipo = $dao
			-> consultaGenerica("SELECT * FROM UsuarioEquipo WHERE idUsuario = ? AND (folio LIKE '%-"
				. $detallesEvento -> getIdDetallesEvento() . "' OR folio IS NULL) ORDER BY idEquipo DESC", array(
			$usuario -> getIdUsuario()
		));
		
		if (!empty($usuarioEquipo)) {
			if (!$usuarioEquipo[0]["noCorredor"]) {
				$inscrito = "ESPERANDO";
			} else {
				$inscrito = "INSCRITO";
				$idEquipo = $usuarioEquipo[0]["idEquipo"];

				$sql = "SELECT fechaRealizacion, horario FROM DiaEvento de, DiaHit dh, Equipo e"
					. " WHERE de.idDiaEvento = (select diaev.idDiaEvento from DiaEvento diaev, DiaHit diah, Equipo eq"
					. " where eq.idEquipo = ? AND eq.idDiaHit = diah.idDiaHit and diah.idDiaEvento = diaev.idDiaEvento)"
					. "AND e.idDiaHit = (SELECT idDiaHit FROM Equipo WHERE idEquipo = ?)"
					. " AND de.idDiaEvento = dh.idDiaEvento AND e.idDiaHit = dh.idDiaHit";
				$diaHit = $dao -> consultaGenerica($sql, array($idEquipo, $idEquipo))[0];
			}
		} else {
			$inscrito = "NUEVO";
		}*/
		
		$session -> offsetSet("inscripcionDetalles", array(
			"detallesEvento" => $detallesEvento,
			"evento" => $nombreEvento,
			"estado" => $estado,
			"diasEvento" => $diasEvento
		));
	} catch (\Exception $ex) {
		header("Location: {$this -> basePath()}/application/cuenta/index");
		die();
	}
?>
<script>
	(function() {
		$("#navbarCollapse ul li").each(function() {
			$(this).removeClass("active");
		});
		$("#navbarCollapse ul").children().last().addClass("active");
		$("#navbarCollapse ul li a").children().last().html("Inscripciones");
		$("#navbarCollapse ul li").children().last().attr("href", "<?php echo $this -> basePath(); ?>/application/cuenta/index");
		document.title = "Eventos - InflaRun";
	})();
</script>
<div id="cuentaBody" class="container-fluid">
	<div class="row">
		<h1>Evento: <?php echo $this -> escapeHtml($nombreEvento["nombre"]); ?> - <?php echo $this -> escapeHtml($detallesEvento -> getNombre()); ?></h1>
		<br>
		<div class="col-md-7 col-xs-7">
			<div class="panel panel-success">
				<div class="panel-heading">
					<strong>Detalles del evento</strong>
				</div>
				<div class="panel-body">
					<div class="list-group">
						<a class="list-group-item"><strong>Estado: </strong><?php echo $this -> escapeHtml($estado["nombre"]); ?></a>
						<a class="list-group-item"><strong>Dirección: </strong><?php echo $this -> escapeHtml($detallesEvento -> getDireccion()); ?></a>
						<a class="list-group-item"><strong>Precio: </strong><?php echo ($detallesEvento -> getRealizado()) ? "n/a" : "\$" . $this -> escapeHtml($detallesEvento -> getPrecio()); ?></a>
						<a class="list-group-item"><strong>Contacto: </strong><?php echo $this -> escapeHtml($detallesEvento -> getCorreoContacto()); ?></a>
						<br>
						<div class="panel panel-default">
							<div class="panel-heading">
								<strong>Días del evento:</strong>
							</div>
							<div class="panel-body">
								<div class="list-group">
									<?php foreach($diasEvento as $dia): ?>
										<a class="list-group-item"><?php echo date_format(date_create($dia["fechaRealizacion"]), "d-m-y"); ?></a>
									<?php endforeach; ?>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-5 col-xs-5">
			<?php if (!$detallesEvento -> getRealizado()): ?>
				<a href="<?php echo $this -> basePath(); ?>/application/cuenta/elegirmodalidad" class="btn btn-primary btn-lg btn-block">¡Inscribirme!</a>
			<?php else: ?>
				<div class="alert alert-info">Las inscripciones para esta carrera están cerradas.</div>
			<?php endif; ?>
			<br>
			<a href="<?php echo $this -> basePath(); ?>/application/cuenta/index" class="btn btn-danger btn-lg btn-block">Regresar</a>	
		</div>
	</div>
</div>